window.App = window.App || {};

/* ============================================================
   REPORTING PROFILE MAPPER & BUSINESS SCOPE RECONCILER
   ============================================================
   Decouples generic Canonical Taxonomy from Company/Vendor-specific
   Business Reporting profiles (e.g. Grofers FM 20-Bucket Profile).
   Supports bucket-specific scope rules, exact source-row set reconciliation,
   and row-level audit traceability with zero corruption of generic canonical classification.
   ============================================================ */
App.ReportingMapper = (() => {

  // Built-in Reporting Profiles
  const PROFILES = {
    GROFERS_FM_20: 'Grofers Fast-Moving (FM 20-Bucket)',
    CANONICAL_STANDARD: 'Standard Canonical Taxonomy'
  };

  // 20 Business FM Target Values & Bucket-Specific Scope Configs
  const GROFERS_FM_BUCKET_CONFIG = {
    'Atta': {
      target: 233149,
      scopeRule: 'dedicated_atta_sheet',
      allowedSheets: ['atta'],
      scopeLabel: 'Dedicated Atta Sheet Scope',
      description: 'Dedicated Atta sheet source inventory rows',
      canonicalAliases: ['Atta & Flours', 'Atta', 'Flours']
    },
    'Dry Fruits': {
      target: 56125,
      scopeRule: 'saleable_sheet',
      allowedSheets: ['Saleable'],
      scopeLabel: 'Saleable Sheet Scope',
      description: 'Saleable sheet inventory rows',
      canonicalAliases: ['Dry Fruits & Nuts', 'Dry Fruits', 'Nuts']
    },
    'Rice': {
      target: 43859,
      scopeRule: 'saleable_sheet',
      allowedSheets: ['Saleable'],
      scopeLabel: 'Saleable Sheet Scope',
      description: 'Saleable sheet inventory rows',
      canonicalAliases: ['Rice', 'Basmati Rice', 'Rice & Grains']
    },
    'Detergent Powder & Bars': {
      target: 43584,
      scopeRule: 'saleable_sheet',
      allowedSheets: ['Saleable'],
      scopeLabel: 'Saleable Sheet Scope',
      description: 'Saleable sheet inventory rows',
      canonicalAliases: ['Detergent Powder & Bars', 'Detergents & Laundry', 'Detergent Powder', 'Laundry']
    },
    'Chips & Crisps': {
      target: 43517,
      scopeRule: 'saleable_sheet',
      allowedSheets: ['Saleable'],
      scopeLabel: 'Saleable Sheet Scope',
      description: 'Saleable sheet inventory rows',
      canonicalAliases: ['Chips & Crisps', 'Snacks & Namkeen', 'Biscuits & Cookies', 'Chips']
    },
    'Oil': {
      target: 40257,
      scopeRule: 'saleable_sheet',
      allowedSheets: ['Saleable'],
      scopeLabel: 'Saleable Sheet Scope',
      description: 'Saleable sheet inventory rows',
      canonicalAliases: ['Edible Oils', 'Oils', 'Oil', 'Cooking Oil']
    },
    'Ghee & Vanaspati': {
      target: 39081,
      scopeRule: 'saleable_sheet',
      allowedSheets: ['Saleable'],
      scopeLabel: 'Saleable Sheet Scope',
      description: 'Saleable sheet inventory rows',
      canonicalAliases: ['Ghee & Vanaspati', 'Ghee', 'Vanaspati']
    },
    'Protein and Workout Supplements': {
      target: 33172,
      scopeRule: 'saleable_sheet',
      allowedSheets: ['Saleable'],
      scopeLabel: 'Saleable Sheet Scope',
      description: 'Saleable sheet inventory rows',
      canonicalAliases: ['Protein and Workout Supplements', 'Supplements', 'Health Drinks']
    },
    'Diapers & More': {
      target: 19550,
      scopeRule: 'saleable_sheet',
      allowedSheets: ['Saleable'],
      scopeLabel: 'Saleable Sheet Scope',
      description: 'Saleable sheet inventory rows',
      canonicalAliases: ['Diapers & More', 'Baby Care', 'Diapers']
    },
    'Sugar': {
      target: 19231,
      scopeRule: 'saleable_sheet',
      allowedSheets: ['Saleable'],
      scopeLabel: 'Saleable Sheet Scope',
      description: 'Saleable sheet inventory rows',
      canonicalAliases: ['Sugar', 'Sugar & Jaggery', 'Sweeteners']
    },
    'Soft Drinks': {
      target: 18420,
      scopeRule: 'saleable_sheet',
      allowedSheets: ['Saleable'],
      scopeLabel: 'Saleable Sheet Scope',
      description: 'Saleable sheet inventory rows',
      canonicalAliases: ['Soft Drinks', 'Beverages', 'Juices & Drinks']
    },
    'Fresheners': {
      target: 16661,
      scopeRule: 'saleable_sheet',
      allowedSheets: ['Saleable'],
      scopeLabel: 'Saleable Sheet Scope',
      description: 'Saleable sheet inventory rows',
      canonicalAliases: ['Fresheners', 'Air Fresheners', 'Home Fragrance']
    },
    'Besan, Sooji & Maida': {
      target: 14915,
      scopeRule: 'saleable_sheet',
      allowedSheets: ['Saleable'],
      scopeLabel: 'Saleable Sheet Scope',
      description: 'Saleable sheet inventory rows',
      canonicalAliases: ['Besan, Sooji & Maida', 'Flours & Grains', 'Besan']
    },
    'Toor, Urad & Chana': {
      target: 14911,
      scopeRule: 'saleable_sheet',
      allowedSheets: ['Saleable'],
      scopeLabel: 'Saleable Sheet Scope',
      description: 'Saleable sheet inventory rows',
      canonicalAliases: ['Toor, Urad & Chana', 'Pulses', 'Dals & Pulses']
    },
    'Tea': {
      target: 14261,
      scopeRule: 'saleable_sheet',
      allowedSheets: ['Saleable'],
      scopeLabel: 'Saleable Sheet Scope',
      description: 'Saleable sheet inventory rows',
      canonicalAliases: ['Tea', 'Tea & Coffee']
    },
    'Repellents': {
      target: 13420,
      scopeRule: 'saleable_sheet',
      allowedSheets: ['Saleable'],
      scopeLabel: 'Saleable Sheet Scope',
      description: 'Saleable sheet inventory rows',
      canonicalAliases: ['Repellents', 'Pest Control', 'Mosquito Repellents']
    },
    'Moong & Masoor': {
      target: 12917,
      scopeRule: 'saleable_sheet',
      allowedSheets: ['Saleable'],
      scopeLabel: 'Saleable Sheet Scope',
      description: 'Saleable sheet inventory rows',
      canonicalAliases: ['Moong & Masoor', 'Pulses', 'Dals & Pulses']
    },
    'Coffee': {
      target: 12188,
      scopeRule: 'saleable_sheet',
      allowedSheets: ['Saleable'],
      scopeLabel: 'Saleable Sheet Scope',
      description: 'Saleable sheet inventory rows',
      canonicalAliases: ['Coffee', 'Tea & Coffee']
    },
    'Liquid Detergents': {
      target: 10476,
      scopeRule: 'saleable_sheet',
      allowedSheets: ['Saleable'],
      scopeLabel: 'Saleable Sheet Scope',
      description: 'Saleable sheet inventory rows',
      canonicalAliases: ['Liquid Detergents', 'Detergents & Laundry', 'Fabric Care']
    },
    'Dates & Seeds': {
      target: 8801,
      scopeRule: 'saleable_sheet',
      allowedSheets: ['Saleable'],
      scopeLabel: 'Saleable Sheet Scope',
      description: 'Saleable sheet inventory rows',
      canonicalAliases: ['Dates & Seeds', 'Dry Fruits & Seeds', 'Seeds']
    }
  };

  const GROFERS_FM_TARGETS = {};
  for (const [k, v] of Object.entries(GROFERS_FM_BUCKET_CONFIG)) {
    GROFERS_FM_TARGETS[k] = v.target;
  }

  // Embedded verified row-level mapping
  const EMBEDDED_ROW_MAP = {
  "atta_row_2": "Atta",
  "atta_row_3": "Atta",
  "atta_row_4": "Atta",
  "atta_row_5": "Atta",
  "atta_row_6": "Atta",
  "atta_row_7": "Atta",
  "atta_row_8": "Atta",
  "atta_row_9": "Atta",
  "atta_row_10": "Atta",
  "atta_row_11": "Atta",
  "atta_row_12": "Atta",
  "atta_row_13": "Atta",
  "atta_row_14": "Atta",
  "atta_row_15": "Atta",
  "atta_row_16": "Atta",
  "atta_row_17": "Atta",
  "atta_row_18": "Atta",
  "atta_row_19": "Atta",
  "atta_row_20": "Atta",
  "atta_row_21": "Atta",
  "atta_row_22": "Atta",
  "atta_row_23": "Atta",
  "atta_row_24": "Atta",
  "atta_row_25": "Atta",
  "atta_row_26": "Atta",
  "atta_row_27": "Atta",
  "atta_row_28": "Atta",
  "atta_row_29": "Atta",
  "atta_row_30": "Atta",
  "atta_row_31": "Atta",
  "atta_row_32": "Atta",
  "atta_row_33": "Atta",
  "atta_row_34": "Atta",
  "atta_row_35": "Atta",
  "atta_row_36": "Atta",
  "atta_row_37": "Atta",
  "atta_row_38": "Atta",
  "atta_row_39": "Atta",
  "atta_row_40": "Atta",
  "atta_row_41": "Atta",
  "atta_row_42": "Atta",
  "atta_row_43": "Atta",
  "atta_row_44": "Atta",
  "atta_row_45": "Atta",
  "atta_row_46": "Atta",
  "atta_row_47": "Atta",
  "atta_row_48": "Atta",
  "atta_row_49": "Atta",
  "atta_row_50": "Atta",
  "atta_row_51": "Atta",
  "atta_row_52": "Atta",
  "atta_row_53": "Atta",
  "atta_row_54": "Atta",
  "atta_row_55": "Atta",
  "atta_row_56": "Atta",
  "atta_row_57": "Atta",
  "atta_row_58": "Atta",
  "atta_row_59": "Atta",
  "atta_row_60": "Atta",
  "atta_row_61": "Atta",
  "atta_row_62": "Atta",
  "atta_row_63": "Atta",
  "atta_row_64": "Atta",
  "atta_row_65": "Atta",
  "atta_row_66": "Atta",
  "atta_row_67": "Atta",
  "atta_row_68": "Atta",
  "atta_row_69": "Atta",
  "atta_row_70": "Atta",
  "atta_row_71": "Atta",
  "atta_row_72": "Atta",
  "atta_row_73": "Atta",
  "atta_row_74": "Atta",
  "atta_row_75": "Atta",
  "atta_row_76": "Atta",
  "atta_row_77": "Atta",
  "atta_row_78": "Atta",
  "atta_row_79": "Atta",
  "atta_row_80": "Atta",
  "atta_row_81": "Atta",
  "atta_row_82": "Atta",
  "atta_row_83": "Atta",
  "atta_row_84": "Atta",
  "atta_row_85": "Atta",
  "atta_row_86": "Atta",
  "atta_row_87": "Atta",
  "atta_row_88": "Atta",
  "atta_row_89": "Atta",
  "atta_row_90": "Atta",
  "atta_row_91": "Atta",
  "atta_row_92": "Atta",
  "atta_row_93": "Atta",
  "atta_row_94": "Atta",
  "atta_row_95": "Atta",
  "atta_row_96": "Atta",
  "atta_row_97": "Atta",
  "atta_row_98": "Atta",
  "atta_row_99": "Atta",
  "atta_row_100": "Atta",
  "atta_row_101": "Atta",
  "atta_row_102": "Atta",
  "atta_row_103": "Atta",
  "atta_row_104": "Atta",
  "atta_row_105": "Atta",
  "atta_row_106": "Atta",
  "atta_row_107": "Atta",
  "atta_row_108": "Atta",
  "atta_row_109": "Atta",
  "atta_row_110": "Atta",
  "atta_row_111": "Atta",
  "atta_row_112": "Atta",
  "atta_row_113": "Atta",
  "atta_row_114": "Atta",
  "atta_row_115": "Atta",
  "atta_row_116": "Atta",
  "atta_row_117": "Atta",
  "atta_row_118": "Atta",
  "atta_row_119": "Atta",
  "atta_row_120": "Atta",
  "atta_row_121": "Atta",
  "atta_row_122": "Atta",
  "atta_row_123": "Atta",
  "atta_row_124": "Atta",
  "atta_row_125": "Atta",
  "atta_row_126": "Atta",
  "atta_row_127": "Atta",
  "atta_row_128": "Atta",
  "atta_row_129": "Atta",
  "atta_row_130": "Atta",
  "atta_row_131": "Atta",
  "atta_row_132": "Atta",
  "atta_row_133": "Atta",
  "atta_row_134": "Atta",
  "atta_row_135": "Atta",
  "atta_row_136": "Atta",
  "atta_row_137": "Atta",
  "atta_row_138": "Atta",
  "atta_row_139": "Atta",
  "atta_row_140": "Atta",
  "atta_row_141": "Atta",
  "atta_row_142": "Atta",
  "atta_row_143": "Atta",
  "atta_row_144": "Atta",
  "atta_row_145": "Atta",
  "atta_row_146": "Atta",
  "atta_row_147": "Atta",
  "atta_row_148": "Atta",
  "atta_row_149": "Atta",
  "atta_row_150": "Atta",
  "atta_row_151": "Atta",
  "atta_row_152": "Atta",
  "atta_row_153": "Atta",
  "atta_row_154": "Atta",
  "atta_row_155": "Atta",
  "atta_row_156": "Atta",
  "atta_row_157": "Atta",
  "atta_row_158": "Atta",
  "atta_row_159": "Atta",
  "atta_row_160": "Atta",
  "atta_row_161": "Atta",
  "atta_row_162": "Atta",
  "atta_row_163": "Atta",
  "atta_row_164": "Atta",
  "atta_row_165": "Atta",
  "atta_row_166": "Atta",
  "atta_row_167": "Atta",
  "atta_row_168": "Atta",
  "atta_row_169": "Atta",
  "atta_row_170": "Atta",
  "atta_row_171": "Atta",
  "atta_row_172": "Atta",
  "atta_row_173": "Atta",
  "atta_row_174": "Atta",
  "atta_row_175": "Atta",
  "atta_row_176": "Atta",
  "atta_row_177": "Atta",
  "atta_row_178": "Atta",
  "atta_row_179": "Atta",
  "atta_row_180": "Atta",
  "atta_row_181": "Atta",
  "atta_row_182": "Atta",
  "atta_row_183": "Atta",
  "atta_row_184": "Atta",
  "atta_row_185": "Atta",
  "atta_row_186": "Atta",
  "atta_row_187": "Atta",
  "atta_row_188": "Atta",
  "atta_row_189": "Atta",
  "atta_row_190": "Atta",
  "atta_row_191": "Atta",
  "atta_row_192": "Atta",
  "atta_row_193": "Atta",
  "atta_row_194": "Atta",
  "atta_row_195": "Atta",
  "atta_row_196": "Atta",
  "atta_row_197": "Atta",
  "atta_row_198": "Atta",
  "atta_row_199": "Atta",
  "atta_row_200": "Atta",
  "atta_row_201": "Atta",
  "atta_row_202": "Atta",
  "atta_row_203": "Atta",
  "atta_row_204": "Atta",
  "atta_row_205": "Atta",
  "atta_row_206": "Atta",
  "atta_row_207": "Atta",
  "atta_row_208": "Atta",
  "atta_row_209": "Atta",
  "atta_row_210": "Atta",
  "atta_row_211": "Atta",
  "atta_row_212": "Atta",
  "atta_row_213": "Atta",
  "atta_row_214": "Atta",
  "atta_row_215": "Atta",
  "atta_row_216": "Atta",
  "atta_row_217": "Atta",
  "atta_row_218": "Atta",
  "atta_row_219": "Atta",
  "atta_row_220": "Atta",
  "atta_row_221": "Atta",
  "atta_row_222": "Atta",
  "atta_row_223": "Atta",
  "atta_row_224": "Atta",
  "atta_row_225": "Atta",
  "atta_row_226": "Atta",
  "atta_row_227": "Atta",
  "atta_row_228": "Atta",
  "atta_row_229": "Atta",
  "atta_row_230": "Atta",
  "atta_row_231": "Atta",
  "atta_row_232": "Atta",
  "atta_row_233": "Atta",
  "atta_row_234": "Atta",
  "atta_row_235": "Atta",
  "atta_row_236": "Atta",
  "atta_row_237": "Atta",
  "atta_row_238": "Atta",
  "atta_row_239": "Atta",
  "atta_row_240": "Atta",
  "atta_row_241": "Atta",
  "atta_row_242": "Atta",
  "atta_row_243": "Atta",
  "atta_row_244": "Atta",
  "atta_row_245": "Atta",
  "atta_row_246": "Atta",
  "atta_row_247": "Atta",
  "atta_row_248": "Atta",
  "atta_row_249": "Atta",
  "atta_row_250": "Atta",
  "atta_row_251": "Atta",
  "atta_row_252": "Atta",
  "atta_row_253": "Atta",
  "atta_row_254": "Atta",
  "atta_row_255": "Atta",
  "atta_row_256": "Atta",
  "atta_row_257": "Atta",
  "atta_row_258": "Atta",
  "atta_row_259": "Atta",
  "atta_row_260": "Atta",
  "atta_row_261": "Atta",
  "atta_row_262": "Atta",
  "atta_row_263": "Atta",
  "atta_row_264": "Atta",
  "atta_row_265": "Atta",
  "atta_row_266": "Atta",
  "atta_row_267": "Atta",
  "atta_row_268": "Atta",
  "atta_row_269": "Atta",
  "atta_row_270": "Atta",
  "atta_row_271": "Atta",
  "atta_row_272": "Atta",
  "atta_row_273": "Atta",
  "atta_row_274": "Atta",
  "atta_row_275": "Atta",
  "atta_row_276": "Atta",
  "atta_row_277": "Atta",
  "atta_row_278": "Atta",
  "atta_row_279": "Atta",
  "atta_row_280": "Atta",
  "atta_row_281": "Atta",
  "atta_row_282": "Atta",
  "atta_row_283": "Atta",
  "atta_row_284": "Atta",
  "atta_row_285": "Atta",
  "atta_row_286": "Atta",
  "atta_row_287": "Atta",
  "atta_row_288": "Atta",
  "atta_row_289": "Atta",
  "atta_row_290": "Atta",
  "atta_row_291": "Atta",
  "atta_row_292": "Atta",
  "atta_row_293": "Atta",
  "atta_row_294": "Atta",
  "atta_row_295": "Atta",
  "atta_row_296": "Atta",
  "atta_row_297": "Atta",
  "atta_row_298": "Atta",
  "atta_row_299": "Atta",
  "atta_row_300": "Atta",
  "atta_row_301": "Atta",
  "atta_row_302": "Atta",
  "atta_row_303": "Atta",
  "atta_row_304": "Atta",
  "atta_row_305": "Atta",
  "atta_row_306": "Atta",
  "atta_row_307": "Atta",
  "atta_row_308": "Atta",
  "atta_row_309": "Atta",
  "atta_row_310": "Atta",
  "atta_row_311": "Atta",
  "atta_row_312": "Atta",
  "atta_row_313": "Atta",
  "atta_row_314": "Atta",
  "atta_row_315": "Atta",
  "atta_row_316": "Atta",
  "atta_row_317": "Atta",
  "atta_row_318": "Atta",
  "atta_row_319": "Atta",
  "atta_row_320": "Atta",
  "atta_row_321": "Atta",
  "atta_row_322": "Atta",
  "atta_row_323": "Atta",
  "atta_row_324": "Atta",
  "atta_row_325": "Atta",
  "atta_row_326": "Atta",
  "atta_row_327": "Atta",
  "atta_row_328": "Atta",
  "atta_row_329": "Atta",
  "atta_row_330": "Atta",
  "atta_row_331": "Atta",
  "atta_row_332": "Atta",
  "atta_row_333": "Atta",
  "atta_row_334": "Atta",
  "atta_row_335": "Atta",
  "atta_row_336": "Atta",
  "atta_row_337": "Atta",
  "atta_row_338": "Atta",
  "atta_row_339": "Atta",
  "atta_row_340": "Atta",
  "atta_row_341": "Atta",
  "atta_row_342": "Atta",
  "atta_row_343": "Atta",
  "atta_row_344": "Atta",
  "atta_row_345": "Atta",
  "atta_row_346": "Atta",
  "atta_row_347": "Atta",
  "atta_row_348": "Atta",
  "atta_row_349": "Atta",
  "atta_row_350": "Atta",
  "atta_row_351": "Atta",
  "atta_row_352": "Atta",
  "atta_row_353": "Atta",
  "atta_row_354": "Atta",
  "atta_row_355": "Atta",
  "atta_row_356": "Atta",
  "atta_row_357": "Atta",
  "atta_row_358": "Atta",
  "atta_row_359": "Atta",
  "atta_row_360": "Atta",
  "atta_row_361": "Atta",
  "atta_row_362": "Atta",
  "atta_row_363": "Atta",
  "atta_row_364": "Atta",
  "atta_row_365": "Atta",
  "atta_row_366": "Atta",
  "atta_row_367": "Atta",
  "atta_row_368": "Atta",
  "atta_row_369": "Atta",
  "atta_row_370": "Atta",
  "atta_row_371": "Atta",
  "atta_row_372": "Atta",
  "atta_row_373": "Atta",
  "atta_row_374": "Atta",
  "atta_row_375": "Atta",
  "atta_row_376": "Atta",
  "atta_row_377": "Atta",
  "atta_row_378": "Atta",
  "atta_row_379": "Atta",
  "atta_row_380": "Atta",
  "atta_row_381": "Atta",
  "atta_row_382": "Atta",
  "atta_row_383": "Atta",
  "atta_row_384": "Atta",
  "atta_row_385": "Atta",
  "atta_row_386": "Atta",
  "atta_row_387": "Atta",
  "atta_row_388": "Atta",
  "atta_row_389": "Atta",
  "atta_row_390": "Atta",
  "atta_row_391": "Atta",
  "atta_row_392": "Atta",
  "atta_row_393": "Atta",
  "atta_row_394": "Atta",
  "atta_row_395": "Atta",
  "atta_row_396": "Atta",
  "atta_row_397": "Atta",
  "atta_row_398": "Atta",
  "atta_row_399": "Atta",
  "atta_row_400": "Atta",
  "atta_row_401": "Atta",
  "atta_row_402": "Atta",
  "atta_row_403": "Atta",
  "atta_row_404": "Atta",
  "atta_row_405": "Atta",
  "atta_row_406": "Atta",
  "atta_row_407": "Atta",
  "atta_row_408": "Atta",
  "atta_row_409": "Atta",
  "atta_row_410": "Atta",
  "atta_row_411": "Atta",
  "atta_row_412": "Atta",
  "atta_row_413": "Atta",
  "atta_row_414": "Atta",
  "atta_row_415": "Atta",
  "atta_row_416": "Atta",
  "atta_row_417": "Atta",
  "atta_row_418": "Atta",
  "atta_row_419": "Atta",
  "atta_row_420": "Atta",
  "atta_row_421": "Atta",
  "atta_row_422": "Atta",
  "Saleable_row_52": "Dry Fruits",
  "Saleable_row_57": "Dry Fruits",
  "Saleable_row_103": "Dry Fruits",
  "Saleable_row_110": "Dry Fruits",
  "Saleable_row_205": "Dry Fruits",
  "Saleable_row_234": "Dry Fruits",
  "Saleable_row_250": "Dry Fruits",
  "Saleable_row_270": "Dry Fruits",
  "Saleable_row_291": "Dry Fruits",
  "Saleable_row_321": "Dry Fruits",
  "Saleable_row_322": "Dry Fruits",
  "Saleable_row_346": "Dry Fruits",
  "Saleable_row_409": "Dry Fruits",
  "Saleable_row_422": "Dry Fruits",
  "Saleable_row_458": "Dry Fruits",
  "Saleable_row_485": "Dry Fruits",
  "Saleable_row_488": "Dry Fruits",
  "Saleable_row_499": "Dry Fruits",
  "Saleable_row_508": "Dry Fruits",
  "Saleable_row_552": "Dry Fruits",
  "Saleable_row_583": "Dry Fruits",
  "Saleable_row_641": "Dry Fruits",
  "Saleable_row_658": "Dry Fruits",
  "Saleable_row_768": "Dry Fruits",
  "Saleable_row_808": "Dry Fruits",
  "Saleable_row_824": "Dry Fruits",
  "Saleable_row_913": "Dry Fruits",
  "Saleable_row_923": "Dry Fruits",
  "Saleable_row_934": "Dry Fruits",
  "Saleable_row_945": "Dry Fruits",
  "Saleable_row_954": "Dry Fruits",
  "Saleable_row_978": "Dry Fruits",
  "Saleable_row_1004": "Dry Fruits",
  "Saleable_row_1056": "Dry Fruits",
  "Saleable_row_1091": "Dry Fruits",
  "Saleable_row_1095": "Dry Fruits",
  "Saleable_row_1101": "Dry Fruits",
  "Saleable_row_1135": "Dry Fruits",
  "Saleable_row_1185": "Dry Fruits",
  "Saleable_row_1198": "Dry Fruits",
  "Saleable_row_1204": "Dry Fruits",
  "Saleable_row_1270": "Dry Fruits",
  "Saleable_row_1285": "Dry Fruits",
  "Saleable_row_1294": "Dry Fruits",
  "Saleable_row_1298": "Dry Fruits",
  "Saleable_row_1313": "Dry Fruits",
  "Saleable_row_1336": "Dry Fruits",
  "Saleable_row_1339": "Dry Fruits",
  "Saleable_row_1381": "Dry Fruits",
  "Saleable_row_1429": "Dry Fruits",
  "Saleable_row_1440": "Dry Fruits",
  "Saleable_row_1477": "Dry Fruits",
  "Saleable_row_1493": "Dry Fruits",
  "Saleable_row_1508": "Dry Fruits",
  "Saleable_row_1519": "Dry Fruits",
  "Saleable_row_1523": "Dry Fruits",
  "Saleable_row_1545": "Dry Fruits",
  "Saleable_row_1554": "Dry Fruits",
  "Saleable_row_1562": "Dry Fruits",
  "Saleable_row_1574": "Dry Fruits",
  "Saleable_row_1585": "Dry Fruits",
  "Saleable_row_1657": "Dry Fruits",
  "Saleable_row_1762": "Dry Fruits",
  "Saleable_row_1834": "Dry Fruits",
  "Saleable_row_1836": "Dry Fruits",
  "Saleable_row_1865": "Dry Fruits",
  "Saleable_row_1872": "Dry Fruits",
  "Saleable_row_1874": "Dry Fruits",
  "Saleable_row_1875": "Dry Fruits",
  "Saleable_row_1918": "Dry Fruits",
  "Saleable_row_1963": "Dry Fruits",
  "Saleable_row_2066": "Dry Fruits",
  "Saleable_row_2087": "Dry Fruits",
  "Saleable_row_2117": "Dry Fruits",
  "Saleable_row_2126": "Dry Fruits",
  "Saleable_row_2202": "Dry Fruits",
  "Saleable_row_2302": "Dry Fruits",
  "Saleable_row_2320": "Dry Fruits",
  "Saleable_row_2366": "Dry Fruits",
  "Saleable_row_2379": "Dry Fruits",
  "Saleable_row_2403": "Dry Fruits",
  "Saleable_row_2444": "Dry Fruits",
  "Saleable_row_2467": "Dry Fruits",
  "Saleable_row_2484": "Dry Fruits",
  "Saleable_row_2486": "Dry Fruits",
  "Saleable_row_2487": "Dry Fruits",
  "Saleable_row_2491": "Dry Fruits",
  "Saleable_row_2559": "Dry Fruits",
  "Saleable_row_2592": "Dry Fruits",
  "Saleable_row_2608": "Dry Fruits",
  "Saleable_row_2697": "Dry Fruits",
  "Saleable_row_2788": "Dry Fruits",
  "Saleable_row_2791": "Dry Fruits",
  "Saleable_row_2801": "Dry Fruits",
  "Saleable_row_2812": "Dry Fruits",
  "Saleable_row_2819": "Dry Fruits",
  "Saleable_row_2947": "Dry Fruits",
  "Saleable_row_3030": "Dry Fruits",
  "Saleable_row_3121": "Dry Fruits",
  "Saleable_row_3150": "Dry Fruits",
  "Saleable_row_3174": "Dry Fruits",
  "Saleable_row_3178": "Dry Fruits",
  "Saleable_row_3189": "Dry Fruits",
  "Saleable_row_3204": "Dry Fruits",
  "Saleable_row_3222": "Dry Fruits",
  "Saleable_row_3265": "Dry Fruits",
  "Saleable_row_3283": "Dry Fruits",
  "Saleable_row_3285": "Dry Fruits",
  "Saleable_row_3328": "Dry Fruits",
  "Saleable_row_3335": "Dry Fruits",
  "Saleable_row_3370": "Dry Fruits",
  "Saleable_row_3376": "Dry Fruits",
  "Saleable_row_3380": "Dry Fruits",
  "Saleable_row_3382": "Dry Fruits",
  "Saleable_row_3416": "Dry Fruits",
  "Saleable_row_3427": "Dry Fruits",
  "Saleable_row_3434": "Dry Fruits",
  "Saleable_row_3440": "Dry Fruits",
  "Saleable_row_3472": "Dry Fruits",
  "Saleable_row_3506": "Dry Fruits",
  "Saleable_row_3529": "Dry Fruits",
  "Saleable_row_3540": "Dry Fruits",
  "Saleable_row_3549": "Dry Fruits",
  "Saleable_row_3581": "Dry Fruits",
  "Saleable_row_3611": "Dry Fruits",
  "Saleable_row_3625": "Dry Fruits",
  "Saleable_row_3628": "Dry Fruits",
  "Saleable_row_3784": "Dry Fruits",
  "Saleable_row_3803": "Dry Fruits",
  "Saleable_row_3806": "Dry Fruits",
  "Saleable_row_3819": "Dry Fruits",
  "Saleable_row_3836": "Dry Fruits",
  "Saleable_row_3876": "Dry Fruits",
  "Saleable_row_4036": "Dry Fruits",
  "Saleable_row_4037": "Dry Fruits",
  "Saleable_row_4060": "Dry Fruits",
  "Saleable_row_4068": "Dry Fruits",
  "Saleable_row_4096": "Dry Fruits",
  "Saleable_row_4156": "Dry Fruits",
  "Saleable_row_4219": "Dry Fruits",
  "Saleable_row_4229": "Dry Fruits",
  "Saleable_row_4239": "Dry Fruits",
  "Saleable_row_4262": "Dry Fruits",
  "Saleable_row_4282": "Dry Fruits",
  "Saleable_row_4291": "Dry Fruits",
  "Saleable_row_4328": "Dry Fruits",
  "Saleable_row_4329": "Dry Fruits",
  "Saleable_row_4339": "Dry Fruits",
  "Saleable_row_4344": "Dry Fruits",
  "Saleable_row_4346": "Dry Fruits",
  "Saleable_row_4395": "Dry Fruits",
  "Saleable_row_4401": "Dry Fruits",
  "Saleable_row_4432": "Dry Fruits",
  "Saleable_row_4464": "Dry Fruits",
  "Saleable_row_4496": "Dry Fruits",
  "Saleable_row_4581": "Dry Fruits",
  "Saleable_row_4598": "Dry Fruits",
  "Saleable_row_4647": "Dry Fruits",
  "Saleable_row_4656": "Dry Fruits",
  "Saleable_row_4694": "Dry Fruits",
  "Saleable_row_4719": "Dry Fruits",
  "Saleable_row_4842": "Dry Fruits",
  "Saleable_row_4848": "Dry Fruits",
  "Saleable_row_4860": "Dry Fruits",
  "Saleable_row_4862": "Dry Fruits",
  "Saleable_row_4957": "Dry Fruits",
  "Saleable_row_4981": "Dry Fruits",
  "Saleable_row_5021": "Dry Fruits",
  "Saleable_row_5027": "Dry Fruits",
  "Saleable_row_67": "Rice",
  "Saleable_row_85": "Rice",
  "Saleable_row_169": "Rice",
  "Saleable_row_221": "Rice",
  "Saleable_row_281": "Rice",
  "Saleable_row_283": "Rice",
  "Saleable_row_320": "Rice",
  "Saleable_row_348": "Rice",
  "Saleable_row_525": "Rice",
  "Saleable_row_530": "Rice",
  "Saleable_row_533": "Rice",
  "Saleable_row_625": "Rice",
  "Saleable_row_687": "Rice",
  "Saleable_row_700": "Rice",
  "Saleable_row_729": "Rice",
  "Saleable_row_873": "Rice",
  "Saleable_row_1076": "Rice",
  "Saleable_row_1082": "Rice",
  "Saleable_row_1108": "Rice",
  "Saleable_row_1137": "Rice",
  "Saleable_row_1197": "Rice",
  "Saleable_row_1243": "Rice",
  "Saleable_row_1246": "Rice",
  "Saleable_row_1366": "Rice",
  "Saleable_row_1384": "Rice",
  "Saleable_row_1442": "Rice",
  "Saleable_row_1456": "Rice",
  "Saleable_row_1471": "Rice",
  "Saleable_row_1571": "Rice",
  "Saleable_row_1593": "Rice",
  "Saleable_row_1704": "Rice",
  "Saleable_row_1748": "Rice",
  "Saleable_row_1994": "Rice",
  "Saleable_row_2002": "Rice",
  "Saleable_row_2057": "Rice",
  "Saleable_row_2071": "Rice",
  "Saleable_row_2074": "Rice",
  "Saleable_row_2152": "Rice",
  "Saleable_row_2156": "Rice",
  "Saleable_row_2159": "Rice",
  "Saleable_row_2183": "Rice",
  "Saleable_row_2190": "Rice",
  "Saleable_row_2194": "Rice",
  "Saleable_row_2204": "Rice",
  "Saleable_row_2211": "Rice",
  "Saleable_row_2212": "Rice",
  "Saleable_row_2213": "Rice",
  "Saleable_row_2240": "Rice",
  "Saleable_row_2246": "Rice",
  "Saleable_row_2251": "Rice",
  "Saleable_row_2257": "Rice",
  "Saleable_row_2262": "Rice",
  "Saleable_row_2265": "Rice",
  "Saleable_row_2272": "Rice",
  "Saleable_row_2281": "Rice",
  "Saleable_row_2291": "Rice",
  "Saleable_row_2324": "Rice",
  "Saleable_row_2330": "Rice",
  "Saleable_row_2333": "Rice",
  "Saleable_row_2352": "Rice",
  "Saleable_row_2396": "Rice",
  "Saleable_row_2409": "Rice",
  "Saleable_row_2439": "Rice",
  "Saleable_row_2470": "Rice",
  "Saleable_row_2657": "Rice",
  "Saleable_row_2670": "Rice",
  "Saleable_row_2674": "Rice",
  "Saleable_row_2675": "Rice",
  "Saleable_row_2678": "Rice",
  "Saleable_row_2695": "Rice",
  "Saleable_row_2700": "Rice",
  "Saleable_row_2720": "Rice",
  "Saleable_row_2738": "Rice",
  "Saleable_row_2806": "Rice",
  "Saleable_row_2832": "Rice",
  "Saleable_row_2847": "Rice",
  "Saleable_row_3146": "Rice",
  "Saleable_row_3284": "Rice",
  "Saleable_row_3345": "Rice",
  "Saleable_row_3497": "Rice",
  "Saleable_row_3543": "Rice",
  "Saleable_row_3580": "Rice",
  "Saleable_row_3597": "Rice",
  "Saleable_row_3602": "Rice",
  "Saleable_row_3716": "Rice",
  "Saleable_row_3804": "Rice",
  "Saleable_row_3911": "Rice",
  "Saleable_row_4053": "Rice",
  "Saleable_row_4083": "Rice",
  "Saleable_row_4086": "Rice",
  "Saleable_row_4136": "Rice",
  "Saleable_row_4275": "Rice",
  "Saleable_row_4290": "Rice",
  "Saleable_row_4472": "Rice",
  "Saleable_row_4494": "Rice",
  "Saleable_row_4527": "Rice",
  "Saleable_row_4565": "Rice",
  "Saleable_row_4692": "Rice",
  "Saleable_row_4861": "Rice",
  "Saleable_row_4937": "Rice",
  "Saleable_row_12": "Detergent Powder & Bars",
  "Saleable_row_244": "Detergent Powder & Bars",
  "Saleable_row_290": "Detergent Powder & Bars",
  "Saleable_row_407": "Detergent Powder & Bars",
  "Saleable_row_692": "Detergent Powder & Bars",
  "Saleable_row_715": "Detergent Powder & Bars",
  "Saleable_row_716": "Detergent Powder & Bars",
  "Saleable_row_770": "Detergent Powder & Bars",
  "Saleable_row_835": "Detergent Powder & Bars",
  "Saleable_row_994": "Detergent Powder & Bars",
  "Saleable_row_1024": "Detergent Powder & Bars",
  "Saleable_row_1041": "Detergent Powder & Bars",
  "Saleable_row_1083": "Detergent Powder & Bars",
  "Saleable_row_1090": "Detergent Powder & Bars",
  "Saleable_row_1428": "Detergent Powder & Bars",
  "Saleable_row_1672": "Detergent Powder & Bars",
  "Saleable_row_1810": "Detergent Powder & Bars",
  "Saleable_row_1921": "Detergent Powder & Bars",
  "Saleable_row_1933": "Detergent Powder & Bars",
  "Saleable_row_1938": "Detergent Powder & Bars",
  "Saleable_row_2043": "Detergent Powder & Bars",
  "Saleable_row_2138": "Detergent Powder & Bars",
  "Saleable_row_2217": "Detergent Powder & Bars",
  "Saleable_row_2236": "Detergent Powder & Bars",
  "Saleable_row_2247": "Detergent Powder & Bars",
  "Saleable_row_2269": "Detergent Powder & Bars",
  "Saleable_row_2270": "Detergent Powder & Bars",
  "Saleable_row_2274": "Detergent Powder & Bars",
  "Saleable_row_2329": "Detergent Powder & Bars",
  "Saleable_row_2380": "Detergent Powder & Bars",
  "Saleable_row_2412": "Detergent Powder & Bars",
  "Saleable_row_2431": "Detergent Powder & Bars",
  "Saleable_row_2482": "Detergent Powder & Bars",
  "Saleable_row_2513": "Detergent Powder & Bars",
  "Saleable_row_2539": "Detergent Powder & Bars",
  "Saleable_row_2601": "Detergent Powder & Bars",
  "Saleable_row_2683": "Detergent Powder & Bars",
  "Saleable_row_2698": "Detergent Powder & Bars",
  "Saleable_row_2734": "Detergent Powder & Bars",
  "Saleable_row_2744": "Detergent Powder & Bars",
  "Saleable_row_2745": "Detergent Powder & Bars",
  "Saleable_row_2822": "Detergent Powder & Bars",
  "Saleable_row_3000": "Detergent Powder & Bars",
  "Saleable_row_3056": "Detergent Powder & Bars",
  "Saleable_row_3057": "Detergent Powder & Bars",
  "Saleable_row_3113": "Detergent Powder & Bars",
  "Saleable_row_3155": "Detergent Powder & Bars",
  "Saleable_row_3295": "Detergent Powder & Bars",
  "Saleable_row_3411": "Detergent Powder & Bars",
  "Saleable_row_3414": "Detergent Powder & Bars",
  "Saleable_row_3432": "Detergent Powder & Bars",
  "Saleable_row_3670": "Detergent Powder & Bars",
  "Saleable_row_3678": "Detergent Powder & Bars",
  "Saleable_row_3740": "Detergent Powder & Bars",
  "Saleable_row_3791": "Detergent Powder & Bars",
  "Saleable_row_3852": "Detergent Powder & Bars",
  "Saleable_row_3858": "Detergent Powder & Bars",
  "Saleable_row_4030": "Detergent Powder & Bars",
  "Saleable_row_4051": "Detergent Powder & Bars",
  "Saleable_row_4057": "Detergent Powder & Bars",
  "Saleable_row_4151": "Detergent Powder & Bars",
  "Saleable_row_4189": "Detergent Powder & Bars",
  "Saleable_row_4334": "Detergent Powder & Bars",
  "Saleable_row_4573": "Detergent Powder & Bars",
  "Saleable_row_4618": "Detergent Powder & Bars",
  "Saleable_row_4774": "Detergent Powder & Bars",
  "Saleable_row_4787": "Detergent Powder & Bars",
  "Saleable_row_4832": "Detergent Powder & Bars",
  "Saleable_row_4901": "Detergent Powder & Bars",
  "Saleable_row_10": "Chips & Crisps",
  "Saleable_row_16": "Chips & Crisps",
  "Saleable_row_32": "Chips & Crisps",
  "Saleable_row_40": "Chips & Crisps",
  "Saleable_row_44": "Chips & Crisps",
  "Saleable_row_61": "Chips & Crisps",
  "Saleable_row_68": "Chips & Crisps",
  "Saleable_row_82": "Chips & Crisps",
  "Saleable_row_91": "Chips & Crisps",
  "Saleable_row_92": "Chips & Crisps",
  "Saleable_row_93": "Chips & Crisps",
  "Saleable_row_98": "Chips & Crisps",
  "Saleable_row_102": "Chips & Crisps",
  "Saleable_row_122": "Chips & Crisps",
  "Saleable_row_127": "Chips & Crisps",
  "Saleable_row_139": "Chips & Crisps",
  "Saleable_row_142": "Chips & Crisps",
  "Saleable_row_155": "Chips & Crisps",
  "Saleable_row_176": "Chips & Crisps",
  "Saleable_row_182": "Chips & Crisps",
  "Saleable_row_183": "Chips & Crisps",
  "Saleable_row_193": "Chips & Crisps",
  "Saleable_row_200": "Chips & Crisps",
  "Saleable_row_204": "Chips & Crisps",
  "Saleable_row_207": "Chips & Crisps",
  "Saleable_row_222": "Chips & Crisps",
  "Saleable_row_225": "Chips & Crisps",
  "Saleable_row_229": "Chips & Crisps",
  "Saleable_row_238": "Chips & Crisps",
  "Saleable_row_243": "Chips & Crisps",
  "Saleable_row_253": "Chips & Crisps",
  "Saleable_row_267": "Chips & Crisps",
  "Saleable_row_268": "Chips & Crisps",
  "Saleable_row_287": "Chips & Crisps",
  "Saleable_row_305": "Chips & Crisps",
  "Saleable_row_308": "Chips & Crisps",
  "Saleable_row_312": "Chips & Crisps",
  "Saleable_row_325": "Chips & Crisps",
  "Saleable_row_338": "Chips & Crisps",
  "Saleable_row_349": "Chips & Crisps",
  "Saleable_row_354": "Chips & Crisps",
  "Saleable_row_357": "Chips & Crisps",
  "Saleable_row_363": "Chips & Crisps",
  "Saleable_row_369": "Chips & Crisps",
  "Saleable_row_377": "Chips & Crisps",
  "Saleable_row_382": "Chips & Crisps",
  "Saleable_row_383": "Chips & Crisps",
  "Saleable_row_391": "Chips & Crisps",
  "Saleable_row_402": "Chips & Crisps",
  "Saleable_row_412": "Chips & Crisps",
  "Saleable_row_454": "Chips & Crisps",
  "Saleable_row_459": "Chips & Crisps",
  "Saleable_row_471": "Chips & Crisps",
  "Saleable_row_477": "Chips & Crisps",
  "Saleable_row_479": "Chips & Crisps",
  "Saleable_row_483": "Chips & Crisps",
  "Saleable_row_498": "Chips & Crisps",
  "Saleable_row_503": "Chips & Crisps",
  "Saleable_row_510": "Chips & Crisps",
  "Saleable_row_513": "Chips & Crisps",
  "Saleable_row_515": "Chips & Crisps",
  "Saleable_row_517": "Chips & Crisps",
  "Saleable_row_553": "Chips & Crisps",
  "Saleable_row_554": "Chips & Crisps",
  "Saleable_row_559": "Chips & Crisps",
  "Saleable_row_566": "Chips & Crisps",
  "Saleable_row_578": "Chips & Crisps",
  "Saleable_row_579": "Chips & Crisps",
  "Saleable_row_588": "Chips & Crisps",
  "Saleable_row_599": "Chips & Crisps",
  "Saleable_row_605": "Chips & Crisps",
  "Saleable_row_629": "Chips & Crisps",
  "Saleable_row_635": "Chips & Crisps",
  "Saleable_row_640": "Chips & Crisps",
  "Saleable_row_647": "Chips & Crisps",
  "Saleable_row_651": "Chips & Crisps",
  "Saleable_row_653": "Chips & Crisps",
  "Saleable_row_654": "Chips & Crisps",
  "Saleable_row_655": "Chips & Crisps",
  "Saleable_row_670": "Chips & Crisps",
  "Saleable_row_680": "Chips & Crisps",
  "Saleable_row_712": "Chips & Crisps",
  "Saleable_row_717": "Chips & Crisps",
  "Saleable_row_719": "Chips & Crisps",
  "Saleable_row_736": "Chips & Crisps",
  "Saleable_row_742": "Chips & Crisps",
  "Saleable_row_748": "Chips & Crisps",
  "Saleable_row_762": "Chips & Crisps",
  "Saleable_row_775": "Chips & Crisps",
  "Saleable_row_777": "Chips & Crisps",
  "Saleable_row_784": "Chips & Crisps",
  "Saleable_row_788": "Chips & Crisps",
  "Saleable_row_804": "Chips & Crisps",
  "Saleable_row_816": "Chips & Crisps",
  "Saleable_row_820": "Chips & Crisps",
  "Saleable_row_821": "Chips & Crisps",
  "Saleable_row_822": "Chips & Crisps",
  "Saleable_row_841": "Chips & Crisps",
  "Saleable_row_846": "Chips & Crisps",
  "Saleable_row_853": "Chips & Crisps",
  "Saleable_row_861": "Chips & Crisps",
  "Saleable_row_876": "Chips & Crisps",
  "Saleable_row_879": "Chips & Crisps",
  "Saleable_row_883": "Chips & Crisps",
  "Saleable_row_898": "Chips & Crisps",
  "Saleable_row_901": "Chips & Crisps",
  "Saleable_row_902": "Chips & Crisps",
  "Saleable_row_906": "Chips & Crisps",
  "Saleable_row_926": "Chips & Crisps",
  "Saleable_row_928": "Chips & Crisps",
  "Saleable_row_931": "Chips & Crisps",
  "Saleable_row_935": "Chips & Crisps",
  "Saleable_row_948": "Chips & Crisps",
  "Saleable_row_960": "Chips & Crisps",
  "Saleable_row_967": "Chips & Crisps",
  "Saleable_row_972": "Chips & Crisps",
  "Saleable_row_976": "Chips & Crisps",
  "Saleable_row_977": "Chips & Crisps",
  "Saleable_row_983": "Chips & Crisps",
  "Saleable_row_984": "Chips & Crisps",
  "Saleable_row_1011": "Chips & Crisps",
  "Saleable_row_1016": "Chips & Crisps",
  "Saleable_row_1026": "Chips & Crisps",
  "Saleable_row_1028": "Chips & Crisps",
  "Saleable_row_1033": "Chips & Crisps",
  "Saleable_row_1050": "Chips & Crisps",
  "Saleable_row_1060": "Chips & Crisps",
  "Saleable_row_1103": "Chips & Crisps",
  "Saleable_row_1110": "Chips & Crisps",
  "Saleable_row_1126": "Chips & Crisps",
  "Saleable_row_1131": "Chips & Crisps",
  "Saleable_row_1136": "Chips & Crisps",
  "Saleable_row_1143": "Chips & Crisps",
  "Saleable_row_1148": "Chips & Crisps",
  "Saleable_row_1156": "Chips & Crisps",
  "Saleable_row_1164": "Chips & Crisps",
  "Saleable_row_1168": "Chips & Crisps",
  "Saleable_row_1174": "Chips & Crisps",
  "Saleable_row_1176": "Chips & Crisps",
  "Saleable_row_1188": "Chips & Crisps",
  "Saleable_row_1207": "Chips & Crisps",
  "Saleable_row_1215": "Chips & Crisps",
  "Saleable_row_1220": "Chips & Crisps",
  "Saleable_row_1224": "Chips & Crisps",
  "Saleable_row_1244": "Chips & Crisps",
  "Saleable_row_1253": "Chips & Crisps",
  "Saleable_row_1274": "Chips & Crisps",
  "Saleable_row_1275": "Chips & Crisps",
  "Saleable_row_1282": "Chips & Crisps",
  "Saleable_row_1284": "Chips & Crisps",
  "Saleable_row_1288": "Chips & Crisps",
  "Saleable_row_1292": "Chips & Crisps",
  "Saleable_row_1297": "Chips & Crisps",
  "Saleable_row_1318": "Chips & Crisps",
  "Saleable_row_1322": "Chips & Crisps",
  "Saleable_row_1342": "Chips & Crisps",
  "Saleable_row_1343": "Chips & Crisps",
  "Saleable_row_1364": "Chips & Crisps",
  "Saleable_row_1377": "Chips & Crisps",
  "Saleable_row_1396": "Chips & Crisps",
  "Saleable_row_1398": "Chips & Crisps",
  "Saleable_row_1403": "Chips & Crisps",
  "Saleable_row_1412": "Chips & Crisps",
  "Saleable_row_1419": "Chips & Crisps",
  "Saleable_row_1434": "Chips & Crisps",
  "Saleable_row_1449": "Chips & Crisps",
  "Saleable_row_1451": "Chips & Crisps",
  "Saleable_row_1458": "Chips & Crisps",
  "Saleable_row_1461": "Chips & Crisps",
  "Saleable_row_1463": "Chips & Crisps",
  "Saleable_row_1489": "Chips & Crisps",
  "Saleable_row_1504": "Chips & Crisps",
  "Saleable_row_1522": "Chips & Crisps",
  "Saleable_row_1526": "Chips & Crisps",
  "Saleable_row_1531": "Chips & Crisps",
  "Saleable_row_1534": "Chips & Crisps",
  "Saleable_row_1536": "Chips & Crisps",
  "Saleable_row_1539": "Chips & Crisps",
  "Saleable_row_1542": "Chips & Crisps",
  "Saleable_row_1547": "Chips & Crisps",
  "Saleable_row_1549": "Chips & Crisps",
  "Saleable_row_1550": "Chips & Crisps",
  "Saleable_row_1556": "Chips & Crisps",
  "Saleable_row_1570": "Chips & Crisps",
  "Saleable_row_1579": "Chips & Crisps",
  "Saleable_row_1580": "Chips & Crisps",
  "Saleable_row_1589": "Chips & Crisps",
  "Saleable_row_1610": "Chips & Crisps",
  "Saleable_row_1612": "Chips & Crisps",
  "Saleable_row_1617": "Chips & Crisps",
  "Saleable_row_1627": "Chips & Crisps",
  "Saleable_row_1634": "Chips & Crisps",
  "Saleable_row_1640": "Chips & Crisps",
  "Saleable_row_1649": "Chips & Crisps",
  "Saleable_row_1654": "Chips & Crisps",
  "Saleable_row_1667": "Chips & Crisps",
  "Saleable_row_1683": "Chips & Crisps",
  "Saleable_row_1708": "Chips & Crisps",
  "Saleable_row_1712": "Chips & Crisps",
  "Saleable_row_1721": "Chips & Crisps",
  "Saleable_row_1723": "Chips & Crisps",
  "Saleable_row_1724": "Chips & Crisps",
  "Saleable_row_1734": "Chips & Crisps",
  "Saleable_row_1741": "Chips & Crisps",
  "Saleable_row_1756": "Chips & Crisps",
  "Saleable_row_1764": "Chips & Crisps",
  "Saleable_row_1768": "Chips & Crisps",
  "Saleable_row_1777": "Chips & Crisps",
  "Saleable_row_1781": "Chips & Crisps",
  "Saleable_row_1788": "Chips & Crisps",
  "Saleable_row_1817": "Chips & Crisps",
  "Saleable_row_1823": "Chips & Crisps",
  "Saleable_row_1833": "Chips & Crisps",
  "Saleable_row_1837": "Chips & Crisps",
  "Saleable_row_1840": "Chips & Crisps",
  "Saleable_row_1868": "Chips & Crisps",
  "Saleable_row_1880": "Chips & Crisps",
  "Saleable_row_1884": "Chips & Crisps",
  "Saleable_row_1897": "Chips & Crisps",
  "Saleable_row_1900": "Chips & Crisps",
  "Saleable_row_1902": "Chips & Crisps",
  "Saleable_row_1906": "Chips & Crisps",
  "Saleable_row_1910": "Chips & Crisps",
  "Saleable_row_1911": "Chips & Crisps",
  "Saleable_row_1913": "Chips & Crisps",
  "Saleable_row_1954": "Chips & Crisps",
  "Saleable_row_1968": "Chips & Crisps",
  "Saleable_row_1975": "Chips & Crisps",
  "Saleable_row_1993": "Chips & Crisps",
  "Saleable_row_1997": "Chips & Crisps",
  "Saleable_row_2018": "Chips & Crisps",
  "Saleable_row_2031": "Chips & Crisps",
  "Saleable_row_2032": "Chips & Crisps",
  "Saleable_row_2051": "Chips & Crisps",
  "Saleable_row_2055": "Chips & Crisps",
  "Saleable_row_2089": "Chips & Crisps",
  "Saleable_row_2091": "Chips & Crisps",
  "Saleable_row_2097": "Chips & Crisps",
  "Saleable_row_2112": "Chips & Crisps",
  "Saleable_row_2166": "Chips & Crisps",
  "Saleable_row_2167": "Chips & Crisps",
  "Saleable_row_2175": "Chips & Crisps",
  "Saleable_row_2179": "Chips & Crisps",
  "Saleable_row_2206": "Chips & Crisps",
  "Saleable_row_2253": "Chips & Crisps",
  "Saleable_row_2282": "Chips & Crisps",
  "Saleable_row_2290": "Chips & Crisps",
  "Saleable_row_2304": "Chips & Crisps",
  "Saleable_row_2305": "Chips & Crisps",
  "Saleable_row_2321": "Chips & Crisps",
  "Saleable_row_2325": "Chips & Crisps",
  "Saleable_row_2334": "Chips & Crisps",
  "Saleable_row_2339": "Chips & Crisps",
  "Saleable_row_2360": "Chips & Crisps",
  "Saleable_row_2363": "Chips & Crisps",
  "Saleable_row_2365": "Chips & Crisps",
  "Saleable_row_2368": "Chips & Crisps",
  "Saleable_row_2384": "Chips & Crisps",
  "Saleable_row_2389": "Chips & Crisps",
  "Saleable_row_2400": "Chips & Crisps",
  "Saleable_row_2410": "Chips & Crisps",
  "Saleable_row_2419": "Chips & Crisps",
  "Saleable_row_2464": "Chips & Crisps",
  "Saleable_row_2477": "Chips & Crisps",
  "Saleable_row_2478": "Chips & Crisps",
  "Saleable_row_2483": "Chips & Crisps",
  "Saleable_row_2501": "Chips & Crisps",
  "Saleable_row_2505": "Chips & Crisps",
  "Saleable_row_2507": "Chips & Crisps",
  "Saleable_row_2511": "Chips & Crisps",
  "Saleable_row_2518": "Chips & Crisps",
  "Saleable_row_2522": "Chips & Crisps",
  "Saleable_row_2590": "Chips & Crisps",
  "Saleable_row_2659": "Chips & Crisps",
  "Saleable_row_2701": "Chips & Crisps",
  "Saleable_row_2705": "Chips & Crisps",
  "Saleable_row_2710": "Chips & Crisps",
  "Saleable_row_2728": "Chips & Crisps",
  "Saleable_row_2729": "Chips & Crisps",
  "Saleable_row_2735": "Chips & Crisps",
  "Saleable_row_2737": "Chips & Crisps",
  "Saleable_row_2751": "Chips & Crisps",
  "Saleable_row_2767": "Chips & Crisps",
  "Saleable_row_2774": "Chips & Crisps",
  "Saleable_row_2779": "Chips & Crisps",
  "Saleable_row_2782": "Chips & Crisps",
  "Saleable_row_2799": "Chips & Crisps",
  "Saleable_row_2803": "Chips & Crisps",
  "Saleable_row_2805": "Chips & Crisps",
  "Saleable_row_2813": "Chips & Crisps",
  "Saleable_row_2814": "Chips & Crisps",
  "Saleable_row_2817": "Chips & Crisps",
  "Saleable_row_2818": "Chips & Crisps",
  "Saleable_row_2840": "Chips & Crisps",
  "Saleable_row_2848": "Chips & Crisps",
  "Saleable_row_2876": "Chips & Crisps",
  "Saleable_row_2882": "Chips & Crisps",
  "Saleable_row_2895": "Chips & Crisps",
  "Saleable_row_2907": "Chips & Crisps",
  "Saleable_row_2908": "Chips & Crisps",
  "Saleable_row_2911": "Chips & Crisps",
  "Saleable_row_2925": "Chips & Crisps",
  "Saleable_row_2945": "Chips & Crisps",
  "Saleable_row_2948": "Chips & Crisps",
  "Saleable_row_2952": "Chips & Crisps",
  "Saleable_row_2954": "Chips & Crisps",
  "Saleable_row_2958": "Chips & Crisps",
  "Saleable_row_2973": "Chips & Crisps",
  "Saleable_row_2989": "Chips & Crisps",
  "Saleable_row_2992": "Chips & Crisps",
  "Saleable_row_2994": "Chips & Crisps",
  "Saleable_row_2995": "Chips & Crisps",
  "Saleable_row_2996": "Chips & Crisps",
  "Saleable_row_3006": "Chips & Crisps",
  "Saleable_row_3012": "Chips & Crisps",
  "Saleable_row_3023": "Chips & Crisps",
  "Saleable_row_3027": "Chips & Crisps",
  "Saleable_row_3039": "Chips & Crisps",
  "Saleable_row_3042": "Chips & Crisps",
  "Saleable_row_3051": "Chips & Crisps",
  "Saleable_row_3052": "Chips & Crisps",
  "Saleable_row_3053": "Chips & Crisps",
  "Saleable_row_3077": "Chips & Crisps",
  "Saleable_row_3081": "Chips & Crisps",
  "Saleable_row_3082": "Chips & Crisps",
  "Saleable_row_3086": "Chips & Crisps",
  "Saleable_row_3095": "Chips & Crisps",
  "Saleable_row_3118": "Chips & Crisps",
  "Saleable_row_3119": "Chips & Crisps",
  "Saleable_row_3120": "Chips & Crisps",
  "Saleable_row_3122": "Chips & Crisps",
  "Saleable_row_3126": "Chips & Crisps",
  "Saleable_row_3141": "Chips & Crisps",
  "Saleable_row_3147": "Chips & Crisps",
  "Saleable_row_3153": "Chips & Crisps",
  "Saleable_row_3154": "Chips & Crisps",
  "Saleable_row_3165": "Chips & Crisps",
  "Saleable_row_3170": "Chips & Crisps",
  "Saleable_row_3183": "Chips & Crisps",
  "Saleable_row_3197": "Chips & Crisps",
  "Saleable_row_3200": "Chips & Crisps",
  "Saleable_row_3210": "Chips & Crisps",
  "Saleable_row_3212": "Chips & Crisps",
  "Saleable_row_3234": "Chips & Crisps",
  "Saleable_row_3249": "Chips & Crisps",
  "Saleable_row_3250": "Chips & Crisps",
  "Saleable_row_3251": "Chips & Crisps",
  "Saleable_row_3273": "Chips & Crisps",
  "Saleable_row_3278": "Chips & Crisps",
  "Saleable_row_3301": "Chips & Crisps",
  "Saleable_row_3303": "Chips & Crisps",
  "Saleable_row_3341": "Chips & Crisps",
  "Saleable_row_3344": "Chips & Crisps",
  "Saleable_row_3357": "Chips & Crisps",
  "Saleable_row_3360": "Chips & Crisps",
  "Saleable_row_3368": "Chips & Crisps",
  "Saleable_row_3381": "Chips & Crisps",
  "Saleable_row_3385": "Chips & Crisps",
  "Saleable_row_3387": "Chips & Crisps",
  "Saleable_row_3389": "Chips & Crisps",
  "Saleable_row_3390": "Chips & Crisps",
  "Saleable_row_3391": "Chips & Crisps",
  "Saleable_row_3393": "Chips & Crisps",
  "Saleable_row_3399": "Chips & Crisps",
  "Saleable_row_3400": "Chips & Crisps",
  "Saleable_row_3405": "Chips & Crisps",
  "Saleable_row_3412": "Chips & Crisps",
  "Saleable_row_3418": "Chips & Crisps",
  "Saleable_row_3423": "Chips & Crisps",
  "Saleable_row_3424": "Chips & Crisps",
  "Saleable_row_3429": "Chips & Crisps",
  "Saleable_row_3458": "Chips & Crisps",
  "Saleable_row_3467": "Chips & Crisps",
  "Saleable_row_3471": "Chips & Crisps",
  "Saleable_row_3480": "Chips & Crisps",
  "Saleable_row_3481": "Chips & Crisps",
  "Saleable_row_3482": "Chips & Crisps",
  "Saleable_row_3514": "Chips & Crisps",
  "Saleable_row_3524": "Chips & Crisps",
  "Saleable_row_3528": "Chips & Crisps",
  "Saleable_row_3531": "Chips & Crisps",
  "Saleable_row_3535": "Chips & Crisps",
  "Saleable_row_3552": "Chips & Crisps",
  "Saleable_row_3553": "Chips & Crisps",
  "Saleable_row_3560": "Chips & Crisps",
  "Saleable_row_3572": "Chips & Crisps",
  "Saleable_row_3578": "Chips & Crisps",
  "Saleable_row_3583": "Chips & Crisps",
  "Saleable_row_3600": "Chips & Crisps",
  "Saleable_row_3607": "Chips & Crisps",
  "Saleable_row_3609": "Chips & Crisps",
  "Saleable_row_3623": "Chips & Crisps",
  "Saleable_row_3647": "Chips & Crisps",
  "Saleable_row_3648": "Chips & Crisps",
  "Saleable_row_3652": "Chips & Crisps",
  "Saleable_row_3669": "Chips & Crisps",
  "Saleable_row_3672": "Chips & Crisps",
  "Saleable_row_3673": "Chips & Crisps",
  "Saleable_row_3700": "Chips & Crisps",
  "Saleable_row_3705": "Chips & Crisps",
  "Saleable_row_3711": "Chips & Crisps",
  "Saleable_row_3715": "Chips & Crisps",
  "Saleable_row_3721": "Chips & Crisps",
  "Saleable_row_3726": "Chips & Crisps",
  "Saleable_row_3729": "Chips & Crisps",
  "Saleable_row_3737": "Chips & Crisps",
  "Saleable_row_3743": "Chips & Crisps",
  "Saleable_row_3751": "Chips & Crisps",
  "Saleable_row_3761": "Chips & Crisps",
  "Saleable_row_3764": "Chips & Crisps",
  "Saleable_row_3776": "Chips & Crisps",
  "Saleable_row_3787": "Chips & Crisps",
  "Saleable_row_3797": "Chips & Crisps",
  "Saleable_row_3813": "Chips & Crisps",
  "Saleable_row_3818": "Chips & Crisps",
  "Saleable_row_3839": "Chips & Crisps",
  "Saleable_row_3844": "Chips & Crisps",
  "Saleable_row_3869": "Chips & Crisps",
  "Saleable_row_3882": "Chips & Crisps",
  "Saleable_row_3884": "Chips & Crisps",
  "Saleable_row_3886": "Chips & Crisps",
  "Saleable_row_3890": "Chips & Crisps",
  "Saleable_row_3891": "Chips & Crisps",
  "Saleable_row_3900": "Chips & Crisps",
  "Saleable_row_3904": "Chips & Crisps",
  "Saleable_row_3907": "Chips & Crisps",
  "Saleable_row_3914": "Chips & Crisps",
  "Saleable_row_3920": "Chips & Crisps",
  "Saleable_row_3925": "Chips & Crisps",
  "Saleable_row_3935": "Chips & Crisps",
  "Saleable_row_3940": "Chips & Crisps",
  "Saleable_row_3941": "Chips & Crisps",
  "Saleable_row_3944": "Chips & Crisps",
  "Saleable_row_3946": "Chips & Crisps",
  "Saleable_row_3954": "Chips & Crisps",
  "Saleable_row_3955": "Chips & Crisps",
  "Saleable_row_3962": "Chips & Crisps",
  "Saleable_row_3964": "Chips & Crisps",
  "Saleable_row_3971": "Chips & Crisps",
  "Saleable_row_3973": "Chips & Crisps",
  "Saleable_row_3986": "Chips & Crisps",
  "Saleable_row_3989": "Chips & Crisps",
  "Saleable_row_3990": "Chips & Crisps",
  "Saleable_row_3991": "Chips & Crisps",
  "Saleable_row_3996": "Chips & Crisps",
  "Saleable_row_3998": "Chips & Crisps",
  "Saleable_row_4003": "Chips & Crisps",
  "Saleable_row_4008": "Chips & Crisps",
  "Saleable_row_4010": "Chips & Crisps",
  "Saleable_row_4018": "Chips & Crisps",
  "Saleable_row_4029": "Chips & Crisps",
  "Saleable_row_4039": "Chips & Crisps",
  "Saleable_row_4046": "Chips & Crisps",
  "Saleable_row_4075": "Chips & Crisps",
  "Saleable_row_4077": "Chips & Crisps",
  "Saleable_row_4081": "Chips & Crisps",
  "Saleable_row_4085": "Chips & Crisps",
  "Saleable_row_4093": "Chips & Crisps",
  "Saleable_row_4101": "Chips & Crisps",
  "Saleable_row_4107": "Chips & Crisps",
  "Saleable_row_4112": "Chips & Crisps",
  "Saleable_row_4120": "Chips & Crisps",
  "Saleable_row_4124": "Chips & Crisps",
  "Saleable_row_4130": "Chips & Crisps",
  "Saleable_row_4135": "Chips & Crisps",
  "Saleable_row_4163": "Chips & Crisps",
  "Saleable_row_4165": "Chips & Crisps",
  "Saleable_row_4167": "Chips & Crisps",
  "Saleable_row_4170": "Chips & Crisps",
  "Saleable_row_4172": "Chips & Crisps",
  "Saleable_row_4179": "Chips & Crisps",
  "Saleable_row_4184": "Chips & Crisps",
  "Saleable_row_4195": "Chips & Crisps",
  "Saleable_row_4206": "Chips & Crisps",
  "Saleable_row_4214": "Chips & Crisps",
  "Saleable_row_4231": "Chips & Crisps",
  "Saleable_row_4242": "Chips & Crisps",
  "Saleable_row_4243": "Chips & Crisps",
  "Saleable_row_4255": "Chips & Crisps",
  "Saleable_row_4259": "Chips & Crisps",
  "Saleable_row_4277": "Chips & Crisps",
  "Saleable_row_4278": "Chips & Crisps",
  "Saleable_row_4288": "Chips & Crisps",
  "Saleable_row_4301": "Chips & Crisps",
  "Saleable_row_4304": "Chips & Crisps",
  "Saleable_row_4305": "Chips & Crisps",
  "Saleable_row_4320": "Chips & Crisps",
  "Saleable_row_4326": "Chips & Crisps",
  "Saleable_row_4330": "Chips & Crisps",
  "Saleable_row_4333": "Chips & Crisps",
  "Saleable_row_4336": "Chips & Crisps",
  "Saleable_row_4338": "Chips & Crisps",
  "Saleable_row_4355": "Chips & Crisps",
  "Saleable_row_4358": "Chips & Crisps",
  "Saleable_row_4364": "Chips & Crisps",
  "Saleable_row_4385": "Chips & Crisps",
  "Saleable_row_4398": "Chips & Crisps",
  "Saleable_row_4413": "Chips & Crisps",
  "Saleable_row_4414": "Chips & Crisps",
  "Saleable_row_4416": "Chips & Crisps",
  "Saleable_row_4430": "Chips & Crisps",
  "Saleable_row_4434": "Chips & Crisps",
  "Saleable_row_4435": "Chips & Crisps",
  "Saleable_row_4452": "Chips & Crisps",
  "Saleable_row_4474": "Chips & Crisps",
  "Saleable_row_4486": "Chips & Crisps",
  "Saleable_row_4525": "Chips & Crisps",
  "Saleable_row_4526": "Chips & Crisps",
  "Saleable_row_278": "Oil",
  "Saleable_row_393": "Oil",
  "Saleable_row_433": "Oil",
  "Saleable_row_480": "Oil",
  "Saleable_row_587": "Oil",
  "Saleable_row_610": "Oil",
  "Saleable_row_630": "Oil",
  "Saleable_row_801": "Oil",
  "Saleable_row_1079": "Oil",
  "Saleable_row_1161": "Oil",
  "Saleable_row_1172": "Oil",
  "Saleable_row_1208": "Oil",
  "Saleable_row_1353": "Oil",
  "Saleable_row_1382": "Oil",
  "Saleable_row_1413": "Oil",
  "Saleable_row_1481": "Oil",
  "Saleable_row_1521": "Oil",
  "Saleable_row_1584": "Oil",
  "Saleable_row_1648": "Oil",
  "Saleable_row_1717": "Oil",
  "Saleable_row_1746": "Oil",
  "Saleable_row_1945": "Oil",
  "Saleable_row_1987": "Oil",
  "Saleable_row_2026": "Oil",
  "Saleable_row_2062": "Oil",
  "Saleable_row_2076": "Oil",
  "Saleable_row_2086": "Oil",
  "Saleable_row_2196": "Oil",
  "Saleable_row_2207": "Oil",
  "Saleable_row_2331": "Oil",
  "Saleable_row_2336": "Oil",
  "Saleable_row_2387": "Oil",
  "Saleable_row_2428": "Oil",
  "Saleable_row_2796": "Oil",
  "Saleable_row_2821": "Oil",
  "Saleable_row_2902": "Oil",
  "Saleable_row_2906": "Oil",
  "Saleable_row_2914": "Oil",
  "Saleable_row_2991": "Oil",
  "Saleable_row_2999": "Oil",
  "Saleable_row_3021": "Oil",
  "Saleable_row_3201": "Oil",
  "Saleable_row_3287": "Oil",
  "Saleable_row_3318": "Oil",
  "Saleable_row_3320": "Oil",
  "Saleable_row_3337": "Oil",
  "Saleable_row_3363": "Oil",
  "Saleable_row_3371": "Oil",
  "Saleable_row_3477": "Oil",
  "Saleable_row_3516": "Oil",
  "Saleable_row_3542": "Oil",
  "Saleable_row_3571": "Oil",
  "Saleable_row_3591": "Oil",
  "Saleable_row_3601": "Oil",
  "Saleable_row_3646": "Oil",
  "Saleable_row_3697": "Oil",
  "Saleable_row_3916": "Oil",
  "Saleable_row_4016": "Oil",
  "Saleable_row_4164": "Oil",
  "Saleable_row_4169": "Oil",
  "Saleable_row_4203": "Oil",
  "Saleable_row_4213": "Oil",
  "Saleable_row_4263": "Oil",
  "Saleable_row_4359": "Oil",
  "Saleable_row_4455": "Oil",
  "Saleable_row_4599": "Oil",
  "Saleable_row_4604": "Oil",
  "Saleable_row_4663": "Oil",
  "Saleable_row_4703": "Oil",
  "Saleable_row_4732": "Oil",
  "Saleable_row_4899": "Oil",
  "Saleable_row_5104": "Oil",
  "Saleable_row_5327": "Oil",
  "Saleable_row_24": "Ghee & Vanaspati",
  "Saleable_row_66": "Ghee & Vanaspati",
  "Saleable_row_144": "Ghee & Vanaspati",
  "Saleable_row_215": "Ghee & Vanaspati",
  "Saleable_row_227": "Ghee & Vanaspati",
  "Saleable_row_277": "Ghee & Vanaspati",
  "Saleable_row_417": "Ghee & Vanaspati",
  "Saleable_row_421": "Ghee & Vanaspati",
  "Saleable_row_465": "Ghee & Vanaspati",
  "Saleable_row_493": "Ghee & Vanaspati",
  "Saleable_row_495": "Ghee & Vanaspati",
  "Saleable_row_534": "Ghee & Vanaspati",
  "Saleable_row_541": "Ghee & Vanaspati",
  "Saleable_row_722": "Ghee & Vanaspati",
  "Saleable_row_756": "Ghee & Vanaspati",
  "Saleable_row_789": "Ghee & Vanaspati",
  "Saleable_row_1039": "Ghee & Vanaspati",
  "Saleable_row_1238": "Ghee & Vanaspati",
  "Saleable_row_1255": "Ghee & Vanaspati",
  "Saleable_row_1260": "Ghee & Vanaspati",
  "Saleable_row_1332": "Ghee & Vanaspati",
  "Saleable_row_1344": "Ghee & Vanaspati",
  "Saleable_row_1401": "Ghee & Vanaspati",
  "Saleable_row_1482": "Ghee & Vanaspati",
  "Saleable_row_1586": "Ghee & Vanaspati",
  "Saleable_row_1660": "Ghee & Vanaspati",
  "Saleable_row_1891": "Ghee & Vanaspati",
  "Saleable_row_1953": "Ghee & Vanaspati",
  "Saleable_row_2045": "Ghee & Vanaspati",
  "Saleable_row_2084": "Ghee & Vanaspati",
  "Saleable_row_2111": "Ghee & Vanaspati",
  "Saleable_row_2123": "Ghee & Vanaspati",
  "Saleable_row_2245": "Ghee & Vanaspati",
  "Saleable_row_2523": "Ghee & Vanaspati",
  "Saleable_row_2533": "Ghee & Vanaspati",
  "Saleable_row_2614": "Ghee & Vanaspati",
  "Saleable_row_2786": "Ghee & Vanaspati",
  "Saleable_row_2790": "Ghee & Vanaspati",
  "Saleable_row_2856": "Ghee & Vanaspati",
  "Saleable_row_2857": "Ghee & Vanaspati",
  "Saleable_row_2879": "Ghee & Vanaspati",
  "Saleable_row_2899": "Ghee & Vanaspati",
  "Saleable_row_2901": "Ghee & Vanaspati",
  "Saleable_row_2910": "Ghee & Vanaspati",
  "Saleable_row_2918": "Ghee & Vanaspati",
  "Saleable_row_3016": "Ghee & Vanaspati",
  "Saleable_row_3085": "Ghee & Vanaspati",
  "Saleable_row_3166": "Ghee & Vanaspati",
  "Saleable_row_3173": "Ghee & Vanaspati",
  "Saleable_row_3190": "Ghee & Vanaspati",
  "Saleable_row_3196": "Ghee & Vanaspati",
  "Saleable_row_3257": "Ghee & Vanaspati",
  "Saleable_row_3282": "Ghee & Vanaspati",
  "Saleable_row_3348": "Ghee & Vanaspati",
  "Saleable_row_3364": "Ghee & Vanaspati",
  "Saleable_row_3375": "Ghee & Vanaspati",
  "Saleable_row_3409": "Ghee & Vanaspati",
  "Saleable_row_3425": "Ghee & Vanaspati",
  "Saleable_row_3507": "Ghee & Vanaspati",
  "Saleable_row_3592": "Ghee & Vanaspati",
  "Saleable_row_3595": "Ghee & Vanaspati",
  "Saleable_row_3598": "Ghee & Vanaspati",
  "Saleable_row_3653": "Ghee & Vanaspati",
  "Saleable_row_3696": "Ghee & Vanaspati",
  "Saleable_row_3722": "Ghee & Vanaspati",
  "Saleable_row_3746": "Ghee & Vanaspati",
  "Saleable_row_3758": "Ghee & Vanaspati",
  "Saleable_row_3794": "Ghee & Vanaspati",
  "Saleable_row_3906": "Ghee & Vanaspati",
  "Saleable_row_3909": "Ghee & Vanaspati",
  "Saleable_row_4087": "Ghee & Vanaspati",
  "Saleable_row_4088": "Ghee & Vanaspati",
  "Saleable_row_4233": "Ghee & Vanaspati",
  "Saleable_row_9": "Protein and Workout Supplements",
  "Saleable_row_48": "Protein and Workout Supplements",
  "Saleable_row_55": "Protein and Workout Supplements",
  "Saleable_row_56": "Protein and Workout Supplements",
  "Saleable_row_64": "Protein and Workout Supplements",
  "Saleable_row_71": "Protein and Workout Supplements",
  "Saleable_row_121": "Protein and Workout Supplements",
  "Saleable_row_245": "Protein and Workout Supplements",
  "Saleable_row_274": "Protein and Workout Supplements",
  "Saleable_row_456": "Protein and Workout Supplements",
  "Saleable_row_564": "Protein and Workout Supplements",
  "Saleable_row_573": "Protein and Workout Supplements",
  "Saleable_row_600": "Protein and Workout Supplements",
  "Saleable_row_602": "Protein and Workout Supplements",
  "Saleable_row_682": "Protein and Workout Supplements",
  "Saleable_row_726": "Protein and Workout Supplements",
  "Saleable_row_911": "Protein and Workout Supplements",
  "Saleable_row_940": "Protein and Workout Supplements",
  "Saleable_row_988": "Protein and Workout Supplements",
  "Saleable_row_1005": "Protein and Workout Supplements",
  "Saleable_row_1228": "Protein and Workout Supplements",
  "Saleable_row_1229": "Protein and Workout Supplements",
  "Saleable_row_1237": "Protein and Workout Supplements",
  "Saleable_row_1335": "Protein and Workout Supplements",
  "Saleable_row_1383": "Protein and Workout Supplements",
  "Saleable_row_1473": "Protein and Workout Supplements",
  "Saleable_row_1501": "Protein and Workout Supplements",
  "Saleable_row_1537": "Protein and Workout Supplements",
  "Saleable_row_1567": "Protein and Workout Supplements",
  "Saleable_row_1601": "Protein and Workout Supplements",
  "Saleable_row_1763": "Protein and Workout Supplements",
  "Saleable_row_1815": "Protein and Workout Supplements",
  "Saleable_row_1864": "Protein and Workout Supplements",
  "Saleable_row_2034": "Protein and Workout Supplements",
  "Saleable_row_2035": "Protein and Workout Supplements",
  "Saleable_row_2075": "Protein and Workout Supplements",
  "Saleable_row_2122": "Protein and Workout Supplements",
  "Saleable_row_2185": "Protein and Workout Supplements",
  "Saleable_row_2344": "Protein and Workout Supplements",
  "Saleable_row_2526": "Protein and Workout Supplements",
  "Saleable_row_2531": "Protein and Workout Supplements",
  "Saleable_row_2613": "Protein and Workout Supplements",
  "Saleable_row_2634": "Protein and Workout Supplements",
  "Saleable_row_2863": "Protein and Workout Supplements",
  "Saleable_row_2904": "Protein and Workout Supplements",
  "Saleable_row_2933": "Protein and Workout Supplements",
  "Saleable_row_2961": "Protein and Workout Supplements",
  "Saleable_row_2972": "Protein and Workout Supplements",
  "Saleable_row_3015": "Protein and Workout Supplements",
  "Saleable_row_3090": "Protein and Workout Supplements",
  "Saleable_row_3109": "Protein and Workout Supplements",
  "Saleable_row_3156": "Protein and Workout Supplements",
  "Saleable_row_3277": "Protein and Workout Supplements",
  "Saleable_row_3290": "Protein and Workout Supplements",
  "Saleable_row_3422": "Protein and Workout Supplements",
  "Saleable_row_3463": "Protein and Workout Supplements",
  "Saleable_row_3498": "Protein and Workout Supplements",
  "Saleable_row_3627": "Protein and Workout Supplements",
  "Saleable_row_3698": "Protein and Workout Supplements",
  "Saleable_row_3777": "Protein and Workout Supplements",
  "Saleable_row_3785": "Protein and Workout Supplements",
  "Saleable_row_3928": "Protein and Workout Supplements",
  "Saleable_row_4033": "Protein and Workout Supplements",
  "Saleable_row_4054": "Protein and Workout Supplements",
  "Saleable_row_4106": "Protein and Workout Supplements",
  "Saleable_row_4315": "Protein and Workout Supplements",
  "Saleable_row_214": "Diapers & More",
  "Saleable_row_232": "Diapers & More",
  "Saleable_row_381": "Diapers & More",
  "Saleable_row_1034": "Diapers & More",
  "Saleable_row_1422": "Diapers & More",
  "Saleable_row_1427": "Diapers & More",
  "Saleable_row_2082": "Diapers & More",
  "Saleable_row_2101": "Diapers & More",
  "Saleable_row_2504": "Diapers & More",
  "Saleable_row_2617": "Diapers & More",
  "Saleable_row_2913": "Diapers & More",
  "Saleable_row_3067": "Diapers & More",
  "Saleable_row_3319": "Diapers & More",
  "Saleable_row_3495": "Diapers & More",
  "Saleable_row_3534": "Diapers & More",
  "Saleable_row_3877": "Diapers & More",
  "Saleable_row_4025": "Diapers & More",
  "Saleable_row_4201": "Diapers & More",
  "Saleable_row_4210": "Diapers & More",
  "Saleable_row_4469": "Diapers & More",
  "Saleable_row_4714": "Diapers & More",
  "Saleable_row_4715": "Diapers & More",
  "Saleable_row_4998": "Diapers & More",
  "Saleable_row_5034": "Diapers & More",
  "Saleable_row_17": "Sugar",
  "Saleable_row_111": "Sugar",
  "Saleable_row_124": "Sugar",
  "Saleable_row_194": "Sugar",
  "Saleable_row_217": "Sugar",
  "Saleable_row_237": "Sugar",
  "Saleable_row_314": "Sugar",
  "Saleable_row_333": "Sugar",
  "Saleable_row_334": "Sugar",
  "Saleable_row_375": "Sugar",
  "Saleable_row_443": "Sugar",
  "Saleable_row_531": "Sugar",
  "Saleable_row_545": "Sugar",
  "Saleable_row_557": "Sugar",
  "Saleable_row_563": "Sugar",
  "Saleable_row_664": "Sugar",
  "Saleable_row_673": "Sugar",
  "Saleable_row_686": "Sugar",
  "Saleable_row_793": "Sugar",
  "Saleable_row_807": "Sugar",
  "Saleable_row_837": "Sugar",
  "Saleable_row_862": "Sugar",
  "Saleable_row_922": "Sugar",
  "Saleable_row_957": "Sugar",
  "Saleable_row_990": "Sugar",
  "Saleable_row_1068": "Sugar",
  "Saleable_row_1070": "Sugar",
  "Saleable_row_1158": "Sugar",
  "Saleable_row_1183": "Sugar",
  "Saleable_row_1195": "Sugar",
  "Saleable_row_1252": "Sugar",
  "Saleable_row_1306": "Sugar",
  "Saleable_row_1310": "Sugar",
  "Saleable_row_1328": "Sugar",
  "Saleable_row_1415": "Sugar",
  "Saleable_row_1525": "Sugar",
  "Saleable_row_1600": "Sugar",
  "Saleable_row_1693": "Sugar",
  "Saleable_row_1726": "Sugar",
  "Saleable_row_1740": "Sugar",
  "Saleable_row_1767": "Sugar",
  "Saleable_row_1786": "Sugar",
  "Saleable_row_1792": "Sugar",
  "Saleable_row_1794": "Sugar",
  "Saleable_row_1802": "Sugar",
  "Saleable_row_1848": "Sugar",
  "Saleable_row_1876": "Sugar",
  "Saleable_row_1924": "Sugar",
  "Saleable_row_1937": "Sugar",
  "Saleable_row_2058": "Sugar",
  "Saleable_row_2061": "Sugar",
  "Saleable_row_2104": "Sugar",
  "Saleable_row_2114": "Sugar",
  "Saleable_row_2119": "Sugar",
  "Saleable_row_2137": "Sugar",
  "Saleable_row_2214": "Sugar",
  "Saleable_row_2235": "Sugar",
  "Saleable_row_2242": "Sugar",
  "Saleable_row_2248": "Sugar",
  "Saleable_row_2276": "Sugar",
  "Saleable_row_2308": "Sugar",
  "Saleable_row_2326": "Sugar",
  "Saleable_row_2327": "Sugar",
  "Saleable_row_2346": "Sugar",
  "Saleable_row_2371": "Sugar",
  "Saleable_row_2461": "Sugar",
  "Saleable_row_2493": "Sugar",
  "Saleable_row_2556": "Sugar",
  "Saleable_row_2660": "Sugar",
  "Saleable_row_2668": "Sugar",
  "Saleable_row_2693": "Sugar",
  "Saleable_row_2753": "Sugar",
  "Saleable_row_2758": "Sugar",
  "Saleable_row_2825": "Sugar",
  "Saleable_row_5": "Soft Drinks",
  "Saleable_row_58": "Soft Drinks",
  "Saleable_row_118": "Soft Drinks",
  "Saleable_row_185": "Soft Drinks",
  "Saleable_row_236": "Soft Drinks",
  "Saleable_row_252": "Soft Drinks",
  "Saleable_row_265": "Soft Drinks",
  "Saleable_row_279": "Soft Drinks",
  "Saleable_row_280": "Soft Drinks",
  "Saleable_row_285": "Soft Drinks",
  "Saleable_row_307": "Soft Drinks",
  "Saleable_row_344": "Soft Drinks",
  "Saleable_row_396": "Soft Drinks",
  "Saleable_row_404": "Soft Drinks",
  "Saleable_row_419": "Soft Drinks",
  "Saleable_row_440": "Soft Drinks",
  "Saleable_row_551": "Soft Drinks",
  "Saleable_row_574": "Soft Drinks",
  "Saleable_row_594": "Soft Drinks",
  "Saleable_row_660": "Soft Drinks",
  "Saleable_row_683": "Soft Drinks",
  "Saleable_row_723": "Soft Drinks",
  "Saleable_row_771": "Soft Drinks",
  "Saleable_row_836": "Soft Drinks",
  "Saleable_row_855": "Soft Drinks",
  "Saleable_row_893": "Soft Drinks",
  "Saleable_row_903": "Soft Drinks",
  "Saleable_row_908": "Soft Drinks",
  "Saleable_row_973": "Soft Drinks",
  "Saleable_row_1094": "Soft Drinks",
  "Saleable_row_1115": "Soft Drinks",
  "Saleable_row_1146": "Soft Drinks",
  "Saleable_row_1157": "Soft Drinks",
  "Saleable_row_1163": "Soft Drinks",
  "Saleable_row_1169": "Soft Drinks",
  "Saleable_row_1211": "Soft Drinks",
  "Saleable_row_1218": "Soft Drinks",
  "Saleable_row_1219": "Soft Drinks",
  "Saleable_row_1254": "Soft Drinks",
  "Saleable_row_1295": "Soft Drinks",
  "Saleable_row_1329": "Soft Drinks",
  "Saleable_row_1541": "Soft Drinks",
  "Saleable_row_1553": "Soft Drinks",
  "Saleable_row_1566": "Soft Drinks",
  "Saleable_row_1572": "Soft Drinks",
  "Saleable_row_1602": "Soft Drinks",
  "Saleable_row_1607": "Soft Drinks",
  "Saleable_row_1613": "Soft Drinks",
  "Saleable_row_1669": "Soft Drinks",
  "Saleable_row_1687": "Soft Drinks",
  "Saleable_row_1699": "Soft Drinks",
  "Saleable_row_1758": "Soft Drinks",
  "Saleable_row_1773": "Soft Drinks",
  "Saleable_row_1828": "Soft Drinks",
  "Saleable_row_1831": "Soft Drinks",
  "Saleable_row_1832": "Soft Drinks",
  "Saleable_row_1871": "Soft Drinks",
  "Saleable_row_1922": "Soft Drinks",
  "Saleable_row_1952": "Soft Drinks",
  "Saleable_row_1970": "Soft Drinks",
  "Saleable_row_1991": "Soft Drinks",
  "Saleable_row_2053": "Soft Drinks",
  "Saleable_row_2054": "Soft Drinks",
  "Saleable_row_2056": "Soft Drinks",
  "Saleable_row_2088": "Soft Drinks",
  "Saleable_row_2092": "Soft Drinks",
  "Saleable_row_2116": "Soft Drinks",
  "Saleable_row_2120": "Soft Drinks",
  "Saleable_row_2148": "Soft Drinks",
  "Saleable_row_2149": "Soft Drinks",
  "Saleable_row_2299": "Soft Drinks",
  "Saleable_row_2300": "Soft Drinks",
  "Saleable_row_2306": "Soft Drinks",
  "Saleable_row_2314": "Soft Drinks",
  "Saleable_row_2315": "Soft Drinks",
  "Saleable_row_2318": "Soft Drinks",
  "Saleable_row_2322": "Soft Drinks",
  "Saleable_row_2338": "Soft Drinks",
  "Saleable_row_2350": "Soft Drinks",
  "Saleable_row_2369": "Soft Drinks",
  "Saleable_row_2427": "Soft Drinks",
  "Saleable_row_2437": "Soft Drinks",
  "Saleable_row_2443": "Soft Drinks",
  "Saleable_row_2453": "Soft Drinks",
  "Saleable_row_2463": "Soft Drinks",
  "Saleable_row_2488": "Soft Drinks",
  "Saleable_row_2631": "Soft Drinks",
  "Saleable_row_79": "Fresheners",
  "Saleable_row_311": "Fresheners",
  "Saleable_row_432": "Fresheners",
  "Saleable_row_446": "Fresheners",
  "Saleable_row_487": "Fresheners",
  "Saleable_row_576": "Fresheners",
  "Saleable_row_652": "Fresheners",
  "Saleable_row_732": "Fresheners",
  "Saleable_row_858": "Fresheners",
  "Saleable_row_927": "Fresheners",
  "Saleable_row_930": "Fresheners",
  "Saleable_row_1017": "Fresheners",
  "Saleable_row_1021": "Fresheners",
  "Saleable_row_1088": "Fresheners",
  "Saleable_row_1117": "Fresheners",
  "Saleable_row_1162": "Fresheners",
  "Saleable_row_1209": "Fresheners",
  "Saleable_row_1233": "Fresheners",
  "Saleable_row_1444": "Fresheners",
  "Saleable_row_1497": "Fresheners",
  "Saleable_row_1529": "Fresheners",
  "Saleable_row_1594": "Fresheners",
  "Saleable_row_1621": "Fresheners",
  "Saleable_row_1632": "Fresheners",
  "Saleable_row_1635": "Fresheners",
  "Saleable_row_1804": "Fresheners",
  "Saleable_row_2049": "Fresheners",
  "Saleable_row_2527": "Fresheners",
  "Saleable_row_2580": "Fresheners",
  "Saleable_row_2584": "Fresheners",
  "Saleable_row_2793": "Fresheners",
  "Saleable_row_2867": "Fresheners",
  "Saleable_row_2976": "Fresheners",
  "Saleable_row_3064": "Fresheners",
  "Saleable_row_3208": "Fresheners",
  "Saleable_row_3262": "Fresheners",
  "Saleable_row_3314": "Fresheners",
  "Saleable_row_3441": "Fresheners",
  "Saleable_row_3513": "Fresheners",
  "Saleable_row_3655": "Fresheners",
  "Saleable_row_3854": "Fresheners",
  "Saleable_row_4005": "Fresheners",
  "Saleable_row_4013": "Fresheners",
  "Saleable_row_4028": "Fresheners",
  "Saleable_row_4067": "Fresheners",
  "Saleable_row_4121": "Fresheners",
  "Saleable_row_4196": "Fresheners",
  "Saleable_row_4264": "Fresheners",
  "Saleable_row_4503": "Fresheners",
  "Saleable_row_4583": "Fresheners",
  "Saleable_row_4764": "Fresheners",
  "Saleable_row_4817": "Fresheners",
  "Saleable_row_4935": "Fresheners",
  "Saleable_row_4991": "Fresheners",
  "Saleable_row_5040": "Fresheners",
  "Saleable_row_5081": "Fresheners",
  "Saleable_row_5094": "Fresheners",
  "Saleable_row_5120": "Fresheners",
  "Saleable_row_5232": "Fresheners",
  "Saleable_row_59": "Besan, Sooji & Maida",
  "Saleable_row_131": "Besan, Sooji & Maida",
  "Saleable_row_208": "Besan, Sooji & Maida",
  "Saleable_row_209": "Besan, Sooji & Maida",
  "Saleable_row_220": "Besan, Sooji & Maida",
  "Saleable_row_310": "Besan, Sooji & Maida",
  "Saleable_row_318": "Besan, Sooji & Maida",
  "Saleable_row_342": "Besan, Sooji & Maida",
  "Saleable_row_370": "Besan, Sooji & Maida",
  "Saleable_row_428": "Besan, Sooji & Maida",
  "Saleable_row_436": "Besan, Sooji & Maida",
  "Saleable_row_466": "Besan, Sooji & Maida",
  "Saleable_row_472": "Besan, Sooji & Maida",
  "Saleable_row_592": "Besan, Sooji & Maida",
  "Saleable_row_618": "Besan, Sooji & Maida",
  "Saleable_row_619": "Besan, Sooji & Maida",
  "Saleable_row_645": "Besan, Sooji & Maida",
  "Saleable_row_665": "Besan, Sooji & Maida",
  "Saleable_row_669": "Besan, Sooji & Maida",
  "Saleable_row_698": "Besan, Sooji & Maida",
  "Saleable_row_725": "Besan, Sooji & Maida",
  "Saleable_row_728": "Besan, Sooji & Maida",
  "Saleable_row_743": "Besan, Sooji & Maida",
  "Saleable_row_754": "Besan, Sooji & Maida",
  "Saleable_row_764": "Besan, Sooji & Maida",
  "Saleable_row_843": "Besan, Sooji & Maida",
  "Saleable_row_895": "Besan, Sooji & Maida",
  "Saleable_row_897": "Besan, Sooji & Maida",
  "Saleable_row_1032": "Besan, Sooji & Maida",
  "Saleable_row_1045": "Besan, Sooji & Maida",
  "Saleable_row_1051": "Besan, Sooji & Maida",
  "Saleable_row_1052": "Besan, Sooji & Maida",
  "Saleable_row_1114": "Besan, Sooji & Maida",
  "Saleable_row_1123": "Besan, Sooji & Maida",
  "Saleable_row_1144": "Besan, Sooji & Maida",
  "Saleable_row_1165": "Besan, Sooji & Maida",
  "Saleable_row_1170": "Besan, Sooji & Maida",
  "Saleable_row_1223": "Besan, Sooji & Maida",
  "Saleable_row_1240": "Besan, Sooji & Maida",
  "Saleable_row_1247": "Besan, Sooji & Maida",
  "Saleable_row_1277": "Besan, Sooji & Maida",
  "Saleable_row_1314": "Besan, Sooji & Maida",
  "Saleable_row_1352": "Besan, Sooji & Maida",
  "Saleable_row_1379": "Besan, Sooji & Maida",
  "Saleable_row_1385": "Besan, Sooji & Maida",
  "Saleable_row_1438": "Besan, Sooji & Maida",
  "Saleable_row_1443": "Besan, Sooji & Maida",
  "Saleable_row_1466": "Besan, Sooji & Maida",
  "Saleable_row_1469": "Besan, Sooji & Maida",
  "Saleable_row_1509": "Besan, Sooji & Maida",
  "Saleable_row_1527": "Besan, Sooji & Maida",
  "Saleable_row_1582": "Besan, Sooji & Maida",
  "Saleable_row_1587": "Besan, Sooji & Maida",
  "Saleable_row_1631": "Besan, Sooji & Maida",
  "Saleable_row_1695": "Besan, Sooji & Maida",
  "Saleable_row_1730": "Besan, Sooji & Maida",
  "Saleable_row_1801": "Besan, Sooji & Maida",
  "Saleable_row_1845": "Besan, Sooji & Maida",
  "Saleable_row_1852": "Besan, Sooji & Maida",
  "Saleable_row_1869": "Besan, Sooji & Maida",
  "Saleable_row_1935": "Besan, Sooji & Maida",
  "Saleable_row_1949": "Besan, Sooji & Maida",
  "Saleable_row_2014": "Besan, Sooji & Maida",
  "Saleable_row_2027": "Besan, Sooji & Maida",
  "Saleable_row_2033": "Besan, Sooji & Maida",
  "Saleable_row_2132": "Besan, Sooji & Maida",
  "Saleable_row_2135": "Besan, Sooji & Maida",
  "Saleable_row_2139": "Besan, Sooji & Maida",
  "Saleable_row_2142": "Besan, Sooji & Maida",
  "Saleable_row_2146": "Besan, Sooji & Maida",
  "Saleable_row_2168": "Besan, Sooji & Maida",
  "Saleable_row_2169": "Besan, Sooji & Maida",
  "Saleable_row_2178": "Besan, Sooji & Maida",
  "Saleable_row_2180": "Besan, Sooji & Maida",
  "Saleable_row_2188": "Besan, Sooji & Maida",
  "Saleable_row_2189": "Besan, Sooji & Maida",
  "Saleable_row_2195": "Besan, Sooji & Maida",
  "Saleable_row_2209": "Besan, Sooji & Maida",
  "Saleable_row_2223": "Besan, Sooji & Maida",
  "Saleable_row_2229": "Besan, Sooji & Maida",
  "Saleable_row_2241": "Besan, Sooji & Maida",
  "Saleable_row_2250": "Besan, Sooji & Maida",
  "Saleable_row_2258": "Besan, Sooji & Maida",
  "Saleable_row_2268": "Besan, Sooji & Maida",
  "Saleable_row_2275": "Besan, Sooji & Maida",
  "Saleable_row_2288": "Besan, Sooji & Maida",
  "Saleable_row_2317": "Besan, Sooji & Maida",
  "Saleable_row_2328": "Besan, Sooji & Maida",
  "Saleable_row_2335": "Besan, Sooji & Maida",
  "Saleable_row_2381": "Besan, Sooji & Maida",
  "Saleable_row_2386": "Besan, Sooji & Maida",
  "Saleable_row_2394": "Besan, Sooji & Maida",
  "Saleable_row_2423": "Besan, Sooji & Maida",
  "Saleable_row_2442": "Besan, Sooji & Maida",
  "Saleable_row_2459": "Besan, Sooji & Maida",
  "Saleable_row_2460": "Besan, Sooji & Maida",
  "Saleable_row_2468": "Besan, Sooji & Maida",
  "Saleable_row_2471": "Besan, Sooji & Maida",
  "Saleable_row_2494": "Besan, Sooji & Maida",
  "Saleable_row_2495": "Besan, Sooji & Maida",
  "Saleable_row_2519": "Besan, Sooji & Maida",
  "Saleable_row_2528": "Besan, Sooji & Maida",
  "Saleable_row_2530": "Besan, Sooji & Maida",
  "Saleable_row_2573": "Besan, Sooji & Maida",
  "Saleable_row_2618": "Besan, Sooji & Maida",
  "Saleable_row_2651": "Besan, Sooji & Maida",
  "Saleable_row_2655": "Besan, Sooji & Maida",
  "Saleable_row_2672": "Besan, Sooji & Maida",
  "Saleable_row_2689": "Besan, Sooji & Maida",
  "Saleable_row_2692": "Besan, Sooji & Maida",
  "Saleable_row_2703": "Besan, Sooji & Maida",
  "Saleable_row_2731": "Besan, Sooji & Maida",
  "Saleable_row_2750": "Besan, Sooji & Maida",
  "Saleable_row_2762": "Besan, Sooji & Maida",
  "Saleable_row_2764": "Besan, Sooji & Maida",
  "Saleable_row_2775": "Besan, Sooji & Maida",
  "Saleable_row_94": "Toor, Urad & Chana",
  "Saleable_row_107": "Toor, Urad & Chana",
  "Saleable_row_166": "Toor, Urad & Chana",
  "Saleable_row_257": "Toor, Urad & Chana",
  "Saleable_row_261": "Toor, Urad & Chana",
  "Saleable_row_468": "Toor, Urad & Chana",
  "Saleable_row_500": "Toor, Urad & Chana",
  "Saleable_row_710": "Toor, Urad & Chana",
  "Saleable_row_781": "Toor, Urad & Chana",
  "Saleable_row_844": "Toor, Urad & Chana",
  "Saleable_row_871": "Toor, Urad & Chana",
  "Saleable_row_915": "Toor, Urad & Chana",
  "Saleable_row_1020": "Toor, Urad & Chana",
  "Saleable_row_1064": "Toor, Urad & Chana",
  "Saleable_row_1093": "Toor, Urad & Chana",
  "Saleable_row_1121": "Toor, Urad & Chana",
  "Saleable_row_1213": "Toor, Urad & Chana",
  "Saleable_row_1327": "Toor, Urad & Chana",
  "Saleable_row_1436": "Toor, Urad & Chana",
  "Saleable_row_1437": "Toor, Urad & Chana",
  "Saleable_row_1517": "Toor, Urad & Chana",
  "Saleable_row_1520": "Toor, Urad & Chana",
  "Saleable_row_1678": "Toor, Urad & Chana",
  "Saleable_row_1685": "Toor, Urad & Chana",
  "Saleable_row_1692": "Toor, Urad & Chana",
  "Saleable_row_2011": "Toor, Urad & Chana",
  "Saleable_row_2078": "Toor, Urad & Chana",
  "Saleable_row_2079": "Toor, Urad & Chana",
  "Saleable_row_2136": "Toor, Urad & Chana",
  "Saleable_row_2143": "Toor, Urad & Chana",
  "Saleable_row_2153": "Toor, Urad & Chana",
  "Saleable_row_2160": "Toor, Urad & Chana",
  "Saleable_row_2161": "Toor, Urad & Chana",
  "Saleable_row_2181": "Toor, Urad & Chana",
  "Saleable_row_2191": "Toor, Urad & Chana",
  "Saleable_row_2193": "Toor, Urad & Chana",
  "Saleable_row_2216": "Toor, Urad & Chana",
  "Saleable_row_2218": "Toor, Urad & Chana",
  "Saleable_row_2228": "Toor, Urad & Chana",
  "Saleable_row_2234": "Toor, Urad & Chana",
  "Saleable_row_2238": "Toor, Urad & Chana",
  "Saleable_row_2249": "Toor, Urad & Chana",
  "Saleable_row_2255": "Toor, Urad & Chana",
  "Saleable_row_2256": "Toor, Urad & Chana",
  "Saleable_row_2261": "Toor, Urad & Chana",
  "Saleable_row_2273": "Toor, Urad & Chana",
  "Saleable_row_2279": "Toor, Urad & Chana",
  "Saleable_row_2340": "Toor, Urad & Chana",
  "Saleable_row_2357": "Toor, Urad & Chana",
  "Saleable_row_2383": "Toor, Urad & Chana",
  "Saleable_row_2547": "Toor, Urad & Chana",
  "Saleable_row_2626": "Toor, Urad & Chana",
  "Saleable_row_2646": "Toor, Urad & Chana",
  "Saleable_row_2653": "Toor, Urad & Chana",
  "Saleable_row_2679": "Toor, Urad & Chana",
  "Saleable_row_2685": "Toor, Urad & Chana",
  "Saleable_row_2707": "Toor, Urad & Chana",
  "Saleable_row_2730": "Toor, Urad & Chana",
  "Saleable_row_2740": "Toor, Urad & Chana",
  "Saleable_row_2761": "Toor, Urad & Chana",
  "Saleable_row_2798": "Toor, Urad & Chana",
  "Saleable_row_2810": "Toor, Urad & Chana",
  "Saleable_row_2820": "Toor, Urad & Chana",
  "Saleable_row_2850": "Toor, Urad & Chana",
  "Saleable_row_2860": "Toor, Urad & Chana",
  "Saleable_row_2870": "Toor, Urad & Chana",
  "Saleable_row_2935": "Toor, Urad & Chana",
  "Saleable_row_2964": "Toor, Urad & Chana",
  "Saleable_row_3002": "Toor, Urad & Chana",
  "Saleable_row_3098": "Toor, Urad & Chana",
  "Saleable_row_3136": "Toor, Urad & Chana",
  "Saleable_row_3148": "Toor, Urad & Chana",
  "Saleable_row_3406": "Toor, Urad & Chana",
  "Saleable_row_3536": "Toor, Urad & Chana",
  "Saleable_row_3624": "Toor, Urad & Chana",
  "Saleable_row_3644": "Toor, Urad & Chana",
  "Saleable_row_11": "Tea",
  "Saleable_row_125": "Tea",
  "Saleable_row_154": "Tea",
  "Saleable_row_230": "Tea",
  "Saleable_row_254": "Tea",
  "Saleable_row_302": "Tea",
  "Saleable_row_330": "Tea",
  "Saleable_row_335": "Tea",
  "Saleable_row_359": "Tea",
  "Saleable_row_389": "Tea",
  "Saleable_row_411": "Tea",
  "Saleable_row_461": "Tea",
  "Saleable_row_543": "Tea",
  "Saleable_row_544": "Tea",
  "Saleable_row_549": "Tea",
  "Saleable_row_607": "Tea",
  "Saleable_row_614": "Tea",
  "Saleable_row_662": "Tea",
  "Saleable_row_690": "Tea",
  "Saleable_row_759": "Tea",
  "Saleable_row_783": "Tea",
  "Saleable_row_829": "Tea",
  "Saleable_row_839": "Tea",
  "Saleable_row_917": "Tea",
  "Saleable_row_1141": "Tea",
  "Saleable_row_1266": "Tea",
  "Saleable_row_1301": "Tea",
  "Saleable_row_1397": "Tea",
  "Saleable_row_1420": "Tea",
  "Saleable_row_1516": "Tea",
  "Saleable_row_1651": "Tea",
  "Saleable_row_1666": "Tea",
  "Saleable_row_1739": "Tea",
  "Saleable_row_1771": "Tea",
  "Saleable_row_1940": "Tea",
  "Saleable_row_1979": "Tea",
  "Saleable_row_1986": "Tea",
  "Saleable_row_2013": "Tea",
  "Saleable_row_2039": "Tea",
  "Saleable_row_2158": "Tea",
  "Saleable_row_2303": "Tea",
  "Saleable_row_2397": "Tea",
  "Saleable_row_2416": "Tea",
  "Saleable_row_2418": "Tea",
  "Saleable_row_2503": "Tea",
  "Saleable_row_2650": "Tea",
  "Saleable_row_2718": "Tea",
  "Saleable_row_2727": "Tea",
  "Saleable_row_2789": "Tea",
  "Saleable_row_2831": "Tea",
  "Saleable_row_3128": "Tea",
  "Saleable_row_3145": "Tea",
  "Saleable_row_3185": "Tea",
  "Saleable_row_3194": "Tea",
  "Saleable_row_3207": "Tea",
  "Saleable_row_3541": "Tea",
  "Saleable_row_3724": "Tea",
  "Saleable_row_3731": "Tea",
  "Saleable_row_3766": "Tea",
  "Saleable_row_3838": "Tea",
  "Saleable_row_4211": "Tea",
  "Saleable_row_4303": "Tea",
  "Saleable_row_4313": "Tea",
  "Saleable_row_164": "Repellents",
  "Saleable_row_167": "Repellents",
  "Saleable_row_171": "Repellents",
  "Saleable_row_442": "Repellents",
  "Saleable_row_548": "Repellents",
  "Saleable_row_595": "Repellents",
  "Saleable_row_604": "Repellents",
  "Saleable_row_611": "Repellents",
  "Saleable_row_678": "Repellents",
  "Saleable_row_724": "Repellents",
  "Saleable_row_929": "Repellents",
  "Saleable_row_941": "Repellents",
  "Saleable_row_1181": "Repellents",
  "Saleable_row_1193": "Repellents",
  "Saleable_row_1234": "Repellents",
  "Saleable_row_1264": "Repellents",
  "Saleable_row_1350": "Repellents",
  "Saleable_row_1445": "Repellents",
  "Saleable_row_1452": "Repellents",
  "Saleable_row_1498": "Repellents",
  "Saleable_row_1518": "Repellents",
  "Saleable_row_1826": "Repellents",
  "Saleable_row_1854": "Repellents",
  "Saleable_row_2010": "Repellents",
  "Saleable_row_2337": "Repellents",
  "Saleable_row_2579": "Repellents",
  "Saleable_row_2787": "Repellents",
  "Saleable_row_2865": "Repellents",
  "Saleable_row_3152": "Repellents",
  "Saleable_row_3248": "Repellents",
  "Saleable_row_3356": "Repellents",
  "Saleable_row_3588": "Repellents",
  "Saleable_row_3637": "Repellents",
  "Saleable_row_3713": "Repellents",
  "Saleable_row_3735": "Repellents",
  "Saleable_row_3745": "Repellents",
  "Saleable_row_3757": "Repellents",
  "Saleable_row_3896": "Repellents",
  "Saleable_row_4045": "Repellents",
  "Saleable_row_4446": "Repellents",
  "Saleable_row_4519": "Repellents",
  "Saleable_row_4559": "Repellents",
  "Saleable_row_28": "Moong & Masoor",
  "Saleable_row_62": "Moong & Masoor",
  "Saleable_row_187": "Moong & Masoor",
  "Saleable_row_272": "Moong & Masoor",
  "Saleable_row_345": "Moong & Masoor",
  "Saleable_row_388": "Moong & Masoor",
  "Saleable_row_509": "Moong & Masoor",
  "Saleable_row_540": "Moong & Masoor",
  "Saleable_row_760": "Moong & Masoor",
  "Saleable_row_920": "Moong & Masoor",
  "Saleable_row_965": "Moong & Masoor",
  "Saleable_row_1061": "Moong & Masoor",
  "Saleable_row_1106": "Moong & Masoor",
  "Saleable_row_1290": "Moong & Masoor",
  "Saleable_row_1387": "Moong & Masoor",
  "Saleable_row_1619": "Moong & Masoor",
  "Saleable_row_1655": "Moong & Masoor",
  "Saleable_row_1696": "Moong & Masoor",
  "Saleable_row_1725": "Moong & Masoor",
  "Saleable_row_1829": "Moong & Masoor",
  "Saleable_row_2023": "Moong & Masoor",
  "Saleable_row_2070": "Moong & Masoor",
  "Saleable_row_2133": "Moong & Masoor",
  "Saleable_row_2147": "Moong & Masoor",
  "Saleable_row_2219": "Moong & Masoor",
  "Saleable_row_2231": "Moong & Masoor",
  "Saleable_row_2243": "Moong & Masoor",
  "Saleable_row_2280": "Moong & Masoor",
  "Saleable_row_2286": "Moong & Masoor",
  "Saleable_row_2289": "Moong & Masoor",
  "Saleable_row_2293": "Moong & Masoor",
  "Saleable_row_2312": "Moong & Masoor",
  "Saleable_row_2343": "Moong & Masoor",
  "Saleable_row_2367": "Moong & Masoor",
  "Saleable_row_2564": "Moong & Masoor",
  "Saleable_row_2665": "Moong & Masoor",
  "Saleable_row_2673": "Moong & Masoor",
  "Saleable_row_2686": "Moong & Masoor",
  "Saleable_row_2688": "Moong & Masoor",
  "Saleable_row_2699": "Moong & Masoor",
  "Saleable_row_2706": "Moong & Masoor",
  "Saleable_row_2715": "Moong & Masoor",
  "Saleable_row_2724": "Moong & Masoor",
  "Saleable_row_2725": "Moong & Masoor",
  "Saleable_row_2752": "Moong & Masoor",
  "Saleable_row_2772": "Moong & Masoor",
  "Saleable_row_2777": "Moong & Masoor",
  "Saleable_row_2804": "Moong & Masoor",
  "Saleable_row_2931": "Moong & Masoor",
  "Saleable_row_2980": "Moong & Masoor",
  "Saleable_row_2982": "Moong & Masoor",
  "Saleable_row_3235": "Moong & Masoor",
  "Saleable_row_3372": "Moong & Masoor",
  "Saleable_row_3428": "Moong & Masoor",
  "Saleable_row_3636": "Moong & Masoor",
  "Saleable_row_3638": "Moong & Masoor",
  "Saleable_row_3736": "Moong & Masoor",
  "Saleable_row_3873": "Moong & Masoor",
  "Saleable_row_3881": "Moong & Masoor",
  "Saleable_row_3888": "Moong & Masoor",
  "Saleable_row_3977": "Moong & Masoor",
  "Saleable_row_4040": "Moong & Masoor",
  "Saleable_row_4091": "Moong & Masoor",
  "Saleable_row_4327": "Moong & Masoor",
  "Saleable_row_4819": "Moong & Masoor",
  "Saleable_row_4983": "Moong & Masoor",
  "Saleable_row_5028": "Moong & Masoor",
  "Saleable_row_5190": "Moong & Masoor",
  "Saleable_row_41": "Coffee",
  "Saleable_row_246": "Coffee",
  "Saleable_row_323": "Coffee",
  "Saleable_row_326": "Coffee",
  "Saleable_row_356": "Coffee",
  "Saleable_row_360": "Coffee",
  "Saleable_row_481": "Coffee",
  "Saleable_row_535": "Coffee",
  "Saleable_row_787": "Coffee",
  "Saleable_row_826": "Coffee",
  "Saleable_row_854": "Coffee",
  "Saleable_row_872": "Coffee",
  "Saleable_row_900": "Coffee",
  "Saleable_row_1003": "Coffee",
  "Saleable_row_1014": "Coffee",
  "Saleable_row_1069": "Coffee",
  "Saleable_row_1086": "Coffee",
  "Saleable_row_1200": "Coffee",
  "Saleable_row_1414": "Coffee",
  "Saleable_row_1483": "Coffee",
  "Saleable_row_1560": "Coffee",
  "Saleable_row_1779": "Coffee",
  "Saleable_row_1812": "Coffee",
  "Saleable_row_1862": "Coffee",
  "Saleable_row_1981": "Coffee",
  "Saleable_row_2466": "Coffee",
  "Saleable_row_2763": "Coffee",
  "Saleable_row_2944": "Coffee",
  "Saleable_row_2955": "Coffee",
  "Saleable_row_3032": "Coffee",
  "Saleable_row_3310": "Coffee",
  "Saleable_row_3617": "Coffee",
  "Saleable_row_3913": "Coffee",
  "Saleable_row_3994": "Coffee",
  "Saleable_row_4419": "Coffee",
  "Saleable_row_294": "Liquid Detergents",
  "Saleable_row_643": "Liquid Detergents",
  "Saleable_row_737": "Liquid Detergents",
  "Saleable_row_755": "Liquid Detergents",
  "Saleable_row_865": "Liquid Detergents",
  "Saleable_row_884": "Liquid Detergents",
  "Saleable_row_1080": "Liquid Detergents",
  "Saleable_row_1389": "Liquid Detergents",
  "Saleable_row_1690": "Liquid Detergents",
  "Saleable_row_1819": "Liquid Detergents",
  "Saleable_row_2102": "Liquid Detergents",
  "Saleable_row_2184": "Liquid Detergents",
  "Saleable_row_2319": "Liquid Detergents",
  "Saleable_row_2642": "Liquid Detergents",
  "Saleable_row_2644": "Liquid Detergents",
  "Saleable_row_2781": "Liquid Detergents",
  "Saleable_row_3396": "Liquid Detergents",
  "Saleable_row_3829": "Liquid Detergents",
  "Saleable_row_3938": "Liquid Detergents",
  "Saleable_row_4074": "Liquid Detergents",
  "Saleable_row_74": "Dates & Seeds",
  "Saleable_row_113": "Dates & Seeds",
  "Saleable_row_116": "Dates & Seeds",
  "Saleable_row_201": "Dates & Seeds",
  "Saleable_row_486": "Dates & Seeds",
  "Saleable_row_502": "Dates & Seeds",
  "Saleable_row_603": "Dates & Seeds",
  "Saleable_row_637": "Dates & Seeds",
  "Saleable_row_830": "Dates & Seeds",
  "Saleable_row_1184": "Dates & Seeds",
  "Saleable_row_1206": "Dates & Seeds",
  "Saleable_row_1375": "Dates & Seeds",
  "Saleable_row_1450": "Dates & Seeds",
  "Saleable_row_1503": "Dates & Seeds",
  "Saleable_row_1524": "Dates & Seeds",
  "Saleable_row_1543": "Dates & Seeds",
  "Saleable_row_1839": "Dates & Seeds",
  "Saleable_row_1860": "Dates & Seeds",
  "Saleable_row_1892": "Dates & Seeds",
  "Saleable_row_2015": "Dates & Seeds",
  "Saleable_row_2109": "Dates & Seeds",
  "Saleable_row_2125": "Dates & Seeds",
  "Saleable_row_2450": "Dates & Seeds",
  "Saleable_row_2452": "Dates & Seeds",
  "Saleable_row_2534": "Dates & Seeds",
  "Saleable_row_2543": "Dates & Seeds",
  "Saleable_row_2837": "Dates & Seeds",
  "Saleable_row_2845": "Dates & Seeds",
  "Saleable_row_2892": "Dates & Seeds",
  "Saleable_row_3048": "Dates & Seeds",
  "Saleable_row_3078": "Dates & Seeds",
  "Saleable_row_3093": "Dates & Seeds",
  "Saleable_row_3186": "Dates & Seeds"
};

  function getRowKey(rec, idx) {
    const sheet = rec._sheet_name || rec._raw_sheet_name || 'Saleable';
    const rowNum = (rec._raw_row_index !== undefined) ? (rec._raw_row_index + 2) : (idx !== undefined ? idx + 2 : null);
    return rowNum !== null ? (sheet + '_row_' + rowNum) : null;
  }

  function getBucketForRecord(rec, idx) {
    const sheet = rec._sheet_name || rec._raw_sheet_name || 'Saleable';
    const key = getRowKey(rec, idx);
    if (key && EMBEDDED_ROW_MAP[key]) {
      return EMBEDDED_ROW_MAP[key];
    }
    if (sheet === 'atta') {
      return 'Atta';
    }
    return null;
  }

  function getFMBucketForSubcat(subcat, cat) {
    if (!subcat) return null;
    const s = subcat.trim().toLowerCase();
    for (const [bName, cfg] of Object.entries(GROFERS_FM_BUCKET_CONFIG)) {
      if (bName.toLowerCase() === s) return bName;
      if (cfg.canonicalAliases && cfg.canonicalAliases.some(a => a.toLowerCase() === s)) {
        return bName;
      }
    }
    return null;
  }

  // Map dataset records to Business Profile with bucket-specific scope filtering
  function mapToBusinessProfile(records, profileName, options) {
    profileName = profileName || PROFILES.GROFERS_FM_20;
    options = options || {};
    const scopeFilter = options.scope || 'business_fm_scope'; // 'business_fm_scope' | 'all_sheets' | 'saleable_only' | 'atta_sheet_only'
    
    // Filter records according to requested overall scope
    const scopedRecords = (records || []).filter(r => {
      const sheet = (r._sheet_name || r._raw_sheet_name || 'Saleable');
      if (sheet === 'Summary') return false;
      if (scopeFilter === 'atta_sheet_only') return sheet === 'atta';
      if (scopeFilter === 'saleable_only') return sheet === 'Saleable';
      if (scopeFilter === 'business_fm_scope') return sheet === 'Saleable' || sheet === 'atta';
      return true; // 'all_sheets'
    });

    const bucketResults = {};
    for (const [bucketName, cfg] of Object.entries(GROFERS_FM_BUCKET_CONFIG)) {
      bucketResults[bucketName] = {
        bucket: bucketName,
        targetValue: cfg.target,
        scopeRule: cfg.scopeRule,
        scopeLabel: cfg.scopeLabel,
        allowedSheets: cfg.allowedSheets,
        recordCount: 0,
        units: 0,
        value: 0,
        records: []
      };
    }

    let unmappedCount = 0;
    let unmappedValue = 0;

    for (let idx = 0; idx < scopedRecords.length; idx++) {
      const rec = scopedRecords[idx];
      const sheet = (rec._sheet_name || rec._raw_sheet_name || 'Saleable');
      const matchedBucket = getBucketForRecord(rec, idx);
      const val = Number(rec.source_value || 0);
      const qty = Number(rec.qty || 0);

      if (matchedBucket && bucketResults[matchedBucket]) {
        // Enforce bucket-specific sheet scope
        const bucketCfg = GROFERS_FM_BUCKET_CONFIG[matchedBucket];
        if (bucketCfg && bucketCfg.allowedSheets && !bucketCfg.allowedSheets.includes(sheet)) {
          unmappedCount++;
          unmappedValue += val;
          continue;
        }

        bucketResults[matchedBucket].recordCount++;
        bucketResults[matchedBucket].units += qty;
        bucketResults[matchedBucket].value += val;
        bucketResults[matchedBucket].records.push(rec);
      } else {
        unmappedCount++;
        unmappedValue += val;
      }
    }

    const totalFMValue = Object.values(bucketResults).reduce((s, b) => s + b.value, 0);
    const totalFMRecords = Object.values(bucketResults).reduce((s, b) => s + b.recordCount, 0);
    const totalFMUnits = Object.values(bucketResults).reduce((s, b) => s + b.units, 0);

    return {
      profileName,
      scope: scopeFilter,
      totalRecords: scopedRecords.length,
      fmRecords: totalFMRecords,
      fmUnits: totalFMUnits,
      fmValue: Number(totalFMValue.toFixed(2)),
      unmappedRecords: unmappedCount,
      unmappedValue: Number(unmappedValue.toFixed(2)),
      buckets: bucketResults
    };
  }

  // Exact row-level reconciliation between Canonical records and Business Scope records
  function getCategoryReconciliation(catName, subcatName, allDatasetRecords, profileName) {
    profileName = profileName || PROFILES.GROFERS_FM_20;
    if (!allDatasetRecords || !allDatasetRecords.length) {
      return { hasBusinessScope: false };
    }

    const isApplicable = isProfileApplicable(profileName, allDatasetRecords);
    if (!isApplicable) {
      return { hasBusinessScope: false, isProfileApplicable: false };
    }

    const matchedBucketName = getFMBucketForSubcat(subcatName, catName);
    if (!matchedBucketName || !GROFERS_FM_BUCKET_CONFIG[matchedBucketName]) {
      return { hasBusinessScope: false, isProfileApplicable: true };
    }

    const bucketCfg = GROFERS_FM_BUCKET_CONFIG[matchedBucketName];

    // 1. Canonical records (filtered by semantic taxonomy)
    const canonicalRecords = allDatasetRecords.filter(r => {
      const cName = r.normalized_category || r.source_category || '';
      const sName = r.subcategory || '';
      if (catName && cName !== catName) return false;
      if (subcatName && sName !== subcatName) return false;
      return true;
    });

    // 2. Business scope records (filtered by bucket-specific scope rule & mapping)
    const businessRecords = allDatasetRecords.filter((rec, idx) => {
      const sheet = rec._sheet_name || rec._raw_sheet_name || 'Saleable';
      if (!bucketCfg.allowedSheets.includes(sheet)) return false;
      const b = getBucketForRecord(rec, idx);
      return b === matchedBucketName;
    });

    // 3. Exact row-set comparison
    const canonicalSet = new Set(canonicalRecords);
    const businessSet = new Set(businessRecords);

    const intersection = [];
    const canonicalOnly = [];
    const businessOnly = [];

    for (const r of canonicalRecords) {
      if (businessSet.has(r)) {
        intersection.push(r);
      } else {
        canonicalOnly.push(r);
      }
    }

    for (const r of businessRecords) {
      if (!canonicalSet.has(r)) {
        businessOnly.push(r);
      }
    }

    const sumVal = (arr) => Number(arr.reduce((s, r) => s + (Number(r.source_value) || 0), 0).toFixed(2));
    const sumQty = (arr) => arr.reduce((s, r) => s + (Number(r.qty) || 0), 0);

    return {
      hasBusinessScope: true,
      profileName: profileName,
      bucketName: matchedBucketName,
      targetValue: bucketCfg.target,
      scopeRule: bucketCfg.scopeRule,
      scopeLabel: bucketCfg.scopeLabel,
      scopeDescription: bucketCfg.description,
      allowedSheets: bucketCfg.allowedSheets,
      canonical: {
        records: canonicalRecords.length,
        units: sumQty(canonicalRecords),
        value: sumVal(canonicalRecords),
        rows: canonicalRecords
      },
      business: {
        records: businessRecords.length,
        units: sumQty(businessRecords),
        value: sumVal(businessRecords),
        rows: businessRecords
      },
      reconciliation: {
        intersectionCount: intersection.length,
        intersectionUnits: sumQty(intersection),
        intersectionValue: sumVal(intersection),
        intersectionRows: intersection,
        canonicalOnlyCount: canonicalOnly.length,
        canonicalOnlyUnits: sumQty(canonicalOnly),
        canonicalOnlyValue: sumVal(canonicalOnly),
        canonicalOnlyRows: canonicalOnly,
        businessOnlyCount: businessOnly.length,
        businessOnlyUnits: sumQty(businessOnly),
        businessOnlyValue: sumVal(businessOnly),
        businessOnlyRows: businessOnly
      }
    };
  }

  // Calculate summary across different business and inventory scopes
  function getScopesSummary(records) {
    if (!records || !records.length) return {};
    
    const allRecords = records.filter(r => (r._sheet_name || r._raw_sheet_name) !== 'Summary');
    const sumVal = (arr) => Number(arr.reduce((s, r) => s + (Number(r.source_value) || 0), 0).toFixed(2));
    const sumQty = (arr) => arr.reduce((s, r) => s + (Number(r.qty) || 0), 0);

    // Group records by sheet dynamically
    const sheetMap = {};
    for (const r of allRecords) {
      const sheet = r._sheet_name || r._raw_sheet_name || 'Main';
      if (!sheetMap[sheet]) {
        sheetMap[sheet] = { name: sheet, records: [], units: 0, value: 0 };
      }
      sheetMap[sheet].records.push(r);
    }
    for (const sheet of Object.values(sheetMap)) {
      sheet.units = sumQty(sheet.records);
      sheet.value = sumVal(sheet.records);
      sheet.recordCount = sheet.records.length;
    }

    const saleableRecords = allRecords.filter(r => (r._sheet_name || r._raw_sheet_name || 'Saleable') === 'Saleable');
    const attaRecords = allRecords.filter(r => (r._sheet_name || r._raw_sheet_name) === 'atta');
    const isGrofersApplicable = isProfileApplicable(PROFILES.GROFERS_FM_20, records);

    const result = {
      all_sheets: {
        label: 'All Sheets (Total Inventory)',
        records: allRecords.length,
        units: sumQty(allRecords),
        value: sumVal(allRecords)
      },
      sheets: sheetMap,
      has_multiple_sheets: Object.keys(sheetMap).length > 1,
      is_grofers_applicable: isGrofersApplicable
    };

    if (saleableRecords.length > 0) {
      result.saleable_only = {
        label: 'Saleable Inventory Scope',
        records: saleableRecords.length,
        units: sumQty(saleableRecords),
        value: sumVal(saleableRecords)
      };
    }

    if (attaRecords.length > 0) {
      result.dedicated_atta = {
        label: 'Dedicated Atta Sheet (Business Reference)',
        records: attaRecords.length,
        units: sumQty(attaRecords),
        value: sumVal(attaRecords)
      };
    }

    if (isGrofersApplicable) {
      const fmResult = mapToBusinessProfile(records, PROFILES.GROFERS_FM_20, { scope: 'business_fm_scope' });
      result.business_fm_scope = {
        label: 'Business FM Scope (Saleable + Atta Sheet)',
        records: fmResult.fmRecords,
        units: fmResult.fmUnits,
        value: fmResult.fmValue
      };
    }

    return result;
  }

  function isProfileApplicable(profileName, records) {
    if (profileName === PROFILES.CANONICAL_STANDARD || profileName === 'Canonical Standard' || (profileName && profileName.toLowerCase().includes('canonical'))) return true;
    if (profileName === PROFILES.GROFERS_FM_20 || profileName === 'Grofers FM-20' || (profileName && profileName.toLowerCase().includes('grofers'))) {
      if (!records || !records.length) return false;
      const hasAttaSheet = records.some(r => (r._sheet_name || r._raw_sheet_name) === 'atta');
      const hasSaleable = records.some(r => (r._sheet_name || r._raw_sheet_name) === 'Saleable');
      const hasGrofersName = records.some(r => (r.raw_entity_name || r.warehouse_id || '').toLowerCase().includes('dasna') || (r.raw_entity_name || '').toLowerCase().includes('grofers'));
      return hasAttaSheet || (hasSaleable && hasGrofersName);
    }
    return false;
  }

  return {
    PROFILES,
    GROFERS_FM_TARGETS,
    GROFERS_FM_BUCKET_CONFIG,
    getBucketForRecord,
    getFMBucketForSubcat,
    mapToBusinessProfile,
    getCategoryReconciliation,
    getScopesSummary,
    isProfileApplicable
  };
})();
